#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026 Robin Jarry

"""
Generate pure Go client bindings from grout C API headers.

Compiles a dummy C file with overridden GR_REQ/GR_REQ_STREAM/GR_EVENT
macros, then extracts struct layouts, enum values, and request/response
mappings from the resulting DWARF debug info using pyelftools.

Usage:
    python3 devtools/gen-go.py --cc='cc -std=gnu2x ...' -o go/ headers...
"""

import argparse
import dataclasses
import difflib
import io
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile

from elftools.elf.elffile import ELFFile

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)

HEADER = "// Code generated by devtools/gen-go.py; DO NOT EDIT.\n\n"

# Headers that go into gen_types.go / gen_api.go
CORE_HEADERS = {
    "gr_net_types.h": "types",
    "gr_net_compat.h": "types",
    "gr_api.h": "api",
}

# Headers to skip (not API types)
SKIP_HEADERS = {
    "gr_api_client_impl.h",
    "gr_bitops.h",
    "gr_clock.h",
    "gr_errno.h",
    "gr_macro.h",
    "gr_version.h",
    "gr_string.h",
}

# C types that map to special Go types
SPECIAL_TYPE_MAP = {
    "ip4_addr_t": ("netip.Addr", 4, "getIPv4", "putIPv4"),
    "rte_ipv6_addr": ("netip.Addr", 16, "getIPv6", "putIPv6"),
    "rte_ether_addr": ("EtherAddr", 6, "getEther", "putEther"),
    "l3_addr": ("netip.Addr", 20, "getL3Addr", "putL3Addr"),
    "cpu_set_t": ("CPUSet", 0, "getCPUSet", "putCPUSet"),
}

# C integer types to Go types
INT_TYPE_MAP = {
    "unsigned char": "uint8",
    "signed char": "int8",
    "char": "uint8",
    "unsigned short": "uint16",
    "short": "int16",
    "unsigned int": "uint32",
    "int": "int32",
    "unsigned long": "uint64",
    "long": "int64",
    "long unsigned int": "uint64",
    "long int": "int64",
    "long long unsigned int": "uint64",
    "long long int": "int64",
    "_Bool": "bool",
    # typedefs
    "uint8_t": "uint8",
    "uint16_t": "uint16",
    "uint32_t": "uint32",
    "uint64_t": "uint64",
    "int8_t": "int8",
    "int16_t": "int16",
    "int32_t": "int32",
    "int64_t": "int64",
    "bool": "bool",
    "rte_be16_t": "uint16",
    "gr_clock_ns_t": "int64",
    "size_t": "uint64",
}

# Structs that map to hand-written Go types
STRUCT_TYPE_MAP = {
    "ip4_net": "IPv4Net",
    "ip6_net": "IPv6Net",
}

# Discriminated flexible array mappings
DISCRIMINATED_INFO = {
    "gr_iface": {
        "discriminator": "Type",
        "go_field": "Info",
        "mapping": {
            "IfaceTypePort": "IfaceInfoPort",
            "IfaceTypeVRF": "IfaceInfoVRF",
            "IfaceTypeVLAN": "IfaceInfoVLAN",
            "IfaceTypeBond": "IfaceInfoBond",
            "IfaceTypeBridge": "IfaceInfoBridge",
            "IfaceTypeIPIP": "IfaceInfoIPIP",
            "IfaceTypeVXLAN": "IfaceInfoVXLAN",
        },
    },
    "gr_nexthop": {
        "discriminator": "Type",
        "go_field": "Info",
        "mapping": {
            "NHTL3": "NexthopInfoL3",
            "NHTSR6Output": "NexthopInfoSRV6",
            "NHTSR6Local": "NexthopInfoSRV6Local",
            "NHTDNAT": "NexthopInfoDNAT",
            "NHTGroup": "NexthopInfoGroup",
        },
    },
}

KNOWN_ENUMS = {}
KNOWN_STRUCTS = {}
FLEXIBLE_STRUCTS = set()
MODULES = {}
API_DIRS = []


@dataclasses.dataclass
class Ctx:
    """DWARF extraction accumulators and per-module groupings."""

    raw_enums: dict = dataclasses.field(default_factory=dict)
    raw_structs: dict = dataclasses.field(default_factory=dict)
    enum_values: dict = dataclasses.field(default_factory=dict)
    raw_requests: list = dataclasses.field(default_factory=list)
    raw_events: list = dataclasses.field(default_factory=list)
    defines_int: dict = dataclasses.field(default_factory=dict)
    type_sizes: dict = dataclasses.field(default_factory=dict)
    enums_by_mod: dict = dataclasses.field(default_factory=dict)
    structs_by_mod: dict = dataclasses.field(default_factory=dict)
    reqs_by_mod: dict = dataclasses.field(default_factory=dict)
    events_by_mod: dict = dataclasses.field(default_factory=dict)
    defines_by_mod: dict = dataclasses.field(default_factory=dict)

ACRONYMS = set(
    "AF BGP CPU DHCP DNAT FDB FIB HW ICMP ID IP IP4 IP6 IPIP ISIS LACP "
    "LDP MAC MRT MTU NAT NH NTK OSPF PBR RA RIP RSS RX RXQ SNAT SR6 "
    "SRV6 SW TCP TX TXQ UDP VNI VLAN VXLAN VRF".split()
)


# ---------------------------------------------------------------------------
# Name conversion helpers
# ---------------------------------------------------------------------------


def c_to_go_name(name):
    s = name
    for prefix in ("GR_", "gr_", "CONN_S_", "DHCP_STATE_"):
        if s.startswith(prefix):
            s = s[len(prefix) :]
            break
    if s.endswith("_t"):
        s = s[:-2]
    parts = s.split("_")
    result = []
    for p in parts:
        up = p.upper()
        if up in ACRONYMS:
            result.append(up)
        else:
            result.append(p.capitalize())
    return "".join(result)


def c_struct_to_go_name(name):
    return c_to_go_name(name.lstrip("_"))


def c_enum_const_to_go(enum_name, const_name):
    return c_to_go_name(const_name)


def go_type_for_c_type(c_type, c_type_name):
    canon = c_type_name
    if canon in SPECIAL_TYPE_MAP:
        return SPECIAL_TYPE_MAP[canon][0]
    if canon in STRUCT_TYPE_MAP:
        return STRUCT_TYPE_MAP[canon]
    if canon in INT_TYPE_MAP:
        return INT_TYPE_MAP[canon]
    if canon in KNOWN_ENUMS:
        return KNOWN_ENUMS[canon]
    if canon in KNOWN_STRUCTS:
        return KNOWN_STRUCTS[canon]
    return None


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclasses.dataclass
class StructField:
    name: str
    c_type_name: str
    offset: int
    size: int
    is_bitfield: bool = False
    bitfield_width: int = 0
    bit_offset: int = 0
    is_flexible_array: bool = False
    element_type_name: str = ""
    element_size: int = 0
    is_array: bool = False
    array_size: int = 0
    go_name: str = ""
    go_type: str = ""
    go_elem_type: str = ""
    contains_flex: bool = False


@dataclasses.dataclass
class StructInfo:
    c_name: str
    size: int
    fields: list
    go_name: str = dataclasses.field(init=False)
    has_flexible_array: bool = dataclasses.field(init=False)

    def __post_init__(self):
        self.go_name = c_struct_to_go_name(self.c_name)
        self.has_flexible_array = any(f.is_flexible_array for f in self.fields)

    def update_flex(self):
        if not self.has_flexible_array:
            self.has_flexible_array = any(f.contains_flex for f in self.fields)


@dataclasses.dataclass
class EnumInfo:
    c_name: str
    go_name: str
    underlying: str
    constants: list


@dataclasses.dataclass
class RequestInfo:
    name: str
    type_val: int
    req_struct: str
    resp_struct: str
    is_stream: bool
    go_const: str = ""


@dataclasses.dataclass
class EventInfo:
    name: str
    type_val: int
    payload_struct: str
    go_const: str = ""


# ---------------------------------------------------------------------------
# Module mapping
# ---------------------------------------------------------------------------


def build_modules(header_paths):
    MODULES.clear()
    API_DIRS.clear()

    seen_dirs = set()
    for path in header_paths:
        basename = os.path.basename(path)
        if basename in SKIP_HEADERS:
            continue
        d = os.path.dirname(os.path.abspath(path))
        if d not in seen_dirs:
            seen_dirs.add(d)
            API_DIRS.append(d)
        if basename in CORE_HEADERS:
            mod = CORE_HEADERS[basename]
        else:
            mod = re.sub(r"^gr_", "", basename)
            mod = re.sub(r"\.h$", "", mod)
        if mod not in MODULES:
            MODULES[mod] = {"headers": [], "source_files": set()}
        MODULES[mod]["headers"].append(basename)
        MODULES[mod]["source_files"].add(basename)


def find_header(basename):
    for d in API_DIRS:
        candidate = os.path.join(d, basename)
        if os.path.exists(candidate):
            return candidate
    return None


# ---------------------------------------------------------------------------
# Compile C file and parse DWARF
# ---------------------------------------------------------------------------

# GR_BIT64(n), plain integers, hex, parenthesized expressions
INT_DEFINE_RE = re.compile(
    r"""
    #define\s+
    (GR_\w+)\s+
    (?:
        GR_BIT\d+\(\d+\)|
        \(?\d[\d\s*]*\)?|
        (?:UINT\d+_C\()?0x[0-9a-fA-F]+\)?
    )\s*$
    """,
    re.MULTILINE | re.VERBOSE,
)
STR_DEFINE_RE = re.compile(r'#define\s+(GR_\w+)\s+"([^"]+)"')


def scan_define_names(header_paths):
    """Scan headers for #define GR_* names to expose via const variables."""
    int_defines = []
    str_defines = []

    for path in header_paths:
        if not os.path.exists(path):
            continue
        with open(path) as f:
            content = f.read()

        for m in INT_DEFINE_RE.finditer(content):
            name = m.group(1)
            if "_MODULE" in name or "_RE" in name:
                continue
            int_defines.append(name)

        for m in STR_DEFINE_RE.finditer(content):
            str_defines.append(m.group(1))

    return int_defines, str_defines


def compile_headers(cc_cmd, header_paths):
    """Generate a C file, compile it with debug info, return path to .o."""
    int_defs, str_defs = scan_define_names(header_paths)

    c_src = []
    # Override macros before including headers
    c_src.append(
        """\
#define GR_REQ(r, req, resp) \\
    resp *r##_(req *a) { return (void *)0; }
#define GR_REQ_STREAM(r, req, resp) \\
    resp *r##_stream_(req *a) { return (void *)0; }
#define GR_EVENT(e, obj) \\
    obj *e##_event_(void) { return (void *)0; }
#define GR_API_INLINE static __attribute__((unused))
"""
    )

    # Include all headers
    for path in header_paths:
        basename = os.path.basename(path)
        if basename in SKIP_HEADERS:
            continue
        c_src.append(f"#include <{basename}>")

    c_src.append("")

    # Emit #define values as enum constants so DWARF stores the values.
    # (static const variables don't get DW_AT_const_value with -O0.)
    if int_defs:
        c_src.append("enum __gen_defines {")
        for name in int_defs:
            c_src.append(f"\t__DEF_{name} = {name},")
        c_src.append("};")

    # String defines are extracted directly from source via regex
    # since they can't be represented as enum values in C.

    c_src.append("")

    src_text = "\n".join(c_src)

    obj_fd, obj_path = tempfile.mkstemp(suffix=".o")
    os.close(obj_fd)

    # Build include path args
    inc_args = []
    for d in API_DIRS:
        inc_args.extend(["-I", d])

    cmd = shlex.split(cc_cmd)
    cmd += [
        "-c",
        "-g",
        "-fno-eliminate-unused-debug-types",
        "-O0",
        "-Wno-missing-declarations",
        "-Wno-missing-prototypes",
    ]
    cmd += inc_args
    cmd += ["-x", "c", "-o", obj_path, "-"]

    result = subprocess.run(
        cmd,
        input=src_text,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"error: compilation failed:\n{result.stderr}", file=sys.stderr)
        os.unlink(obj_path)
        sys.exit(1)

    return obj_path


# ---------------------------------------------------------------------------
# DWARF helpers
# ---------------------------------------------------------------------------


def dwarf_resolve_type(die):
    if "DW_AT_type" not in die.attributes:
        return None
    ref = die.attributes["DW_AT_type"].value
    return die.cu.get_DIE_from_refaddr(ref + die.cu.cu_offset)


def dwarf_name(die):
    n = die.attributes.get("DW_AT_name")
    return n.value.decode() if n else None


def dwarf_unwrap_typedef(die):
    while die and die.tag == "DW_TAG_typedef":
        die = dwarf_resolve_type(die)
    return die


def dwarf_type_name(die):
    """Get the C type name, following typedefs."""
    if die is None:
        return "void"
    name = dwarf_name(die)
    if name:
        return name
    if die.tag == "DW_TAG_pointer_type":
        return dwarf_type_name(dwarf_resolve_type(die))
    if die.tag == "DW_TAG_typedef":
        return dwarf_name(die) or dwarf_type_name(dwarf_resolve_type(die))
    if die.tag == "DW_TAG_const_type":
        return dwarf_type_name(dwarf_resolve_type(die))
    return None


def dwarf_byte_size(die):
    """Get DW_AT_byte_size, following type references if needed."""
    if die is None:
        return 0
    sz = die.attributes.get("DW_AT_byte_size")
    if sz:
        return sz.value
    if die.tag == "DW_TAG_typedef":
        return dwarf_byte_size(dwarf_resolve_type(die))
    return 0


def dwarf_go_int_type(size_bytes):
    return {1: "uint8", 2: "uint16", 4: "uint32", 8: "uint64"}.get(
        size_bytes, f"[{size_bytes}]byte"
    )


# ---------------------------------------------------------------------------
# DWARF extraction
# ---------------------------------------------------------------------------


def extract_all_from_dwarf(ctx, obj_path):
    """Parse DWARF info, populating ctx with results."""
    with open(obj_path, "rb") as f:
        elf = ELFFile(f)
        dwarf = elf.get_dwarf_info()
        for cu in dwarf.iter_CUs():
            for die in cu.iter_DIEs():
                _process_die(ctx, die)


def _process_die(ctx, die):
    if die.tag == "DW_TAG_typedef":
        name = dwarf_name(die)
        if not name:
            return
        target = dwarf_resolve_type(die)
        if target and target.tag == "DW_TAG_enumeration_type":
            _extract_enum(ctx, name, target)

    elif die.tag == "DW_TAG_enumeration_type":
        name = dwarf_name(die)
        if name == "__gen_defines":
            for child in die.iter_children():
                if child.tag != "DW_TAG_enumerator":
                    continue
                cname = dwarf_name(child)
                if cname and cname.startswith("__DEF_"):
                    cval = child.attributes.get("DW_AT_const_value")
                    if cval is not None:
                        ctx.defines_int[cname[len("__DEF_") :]] = cval.value
        elif name:
            _extract_enum(ctx, name, die)

    elif die.tag == "DW_TAG_structure_type":
        name = dwarf_name(die)
        if not name:
            return
        sz = die.attributes.get("DW_AT_byte_size")
        if not sz:
            return
        if name in ("gr_api_event", "gr_api_request", "gr_api_response", "cpu_set_t"):
            ctx.type_sizes[name] = sz.value
        if name not in ctx.raw_structs:
            ctx.raw_structs[name] = (die, sz.value)

    elif die.tag == "DW_TAG_subprogram":
        name = dwarf_name(die)
        if not name:
            return
        _extract_function(ctx, name, die)


def _extract_enum(ctx, name, die):
    if name in ctx.raw_enums:
        return
    sz = die.attributes.get("DW_AT_byte_size")
    if not sz:
        return
    constants = []
    for child in die.iter_children():
        if child.tag != "DW_TAG_enumerator":
            continue
        cname = dwarf_name(child)
        cval = child.attributes.get("DW_AT_const_value")
        if cname and cval is not None:
            constants.append((cname, cval.value))
            ctx.enum_values[cname] = cval.value
    if constants:
        ctx.raw_enums[name] = (sz.value, constants)


def _extract_function(ctx, name, die):
    if name.endswith("_event_"):
        req_name = name[: -len("_event_")]
        ret_die = dwarf_resolve_type(die)
        if ret_die and ret_die.tag == "DW_TAG_pointer_type":
            payload = dwarf_type_name(dwarf_resolve_type(ret_die))
            if payload:
                ctx.raw_events.append((req_name, payload))
    elif name.endswith("_stream_"):
        _extract_req_resp(ctx, name[: -len("_stream_")], die, is_stream=True)
    elif name.endswith("_"):
        _extract_req_resp(ctx, name[:-1], die, is_stream=False)


def _extract_req_resp(ctx, req_name, die, is_stream):
    ret_die = dwarf_resolve_type(die)
    resp_name = "gr_empty"
    if ret_die and ret_die.tag == "DW_TAG_pointer_type":
        inner = dwarf_type_name(dwarf_resolve_type(ret_die))
        if inner:
            resp_name = inner

    req_sname = "gr_empty"
    for child in die.iter_children():
        if child.tag == "DW_TAG_formal_parameter":
            ptype = dwarf_resolve_type(child)
            if ptype and ptype.tag == "DW_TAG_pointer_type":
                inner = dwarf_type_name(dwarf_resolve_type(ptype))
                if inner:
                    req_sname = inner
            break

    ctx.raw_requests.append((req_name, req_sname, resp_name, is_stream))


def extract_struct_fields_dwarf(die):
    """Extract fields from a DWARF struct DIE, flattening anonymous members."""
    fields = []
    _walk_members(die, die, fields)
    return fields


def _walk_members(struct_die, top_die, fields):
    for child in struct_die.iter_children():
        if child.tag != "DW_TAG_member":
            continue

        name = dwarf_name(child)
        loc = child.attributes.get("DW_AT_data_member_location")
        offset = loc.value if loc else 0

        mtype = dwarf_resolve_type(child)
        if mtype is None:
            continue

        # Anonymous struct/union from BASE() — flatten
        if name is None:
            real_type = dwarf_unwrap_typedef(mtype)
            if real_type and real_type.tag in (
                "DW_TAG_structure_type",
                "DW_TAG_union_type",
            ):
                _walk_members(real_type, top_die, fields)
            continue

        # Skip the 'base' field from BASE() anonymous union
        if name == "base":
            continue

        real_type = dwarf_unwrap_typedef(mtype)
        type_name = dwarf_type_name(mtype) or ""
        type_size = dwarf_byte_size(mtype)

        # Bitfield
        bit_size = child.attributes.get("DW_AT_bit_size")
        bit_off_attr = child.attributes.get("DW_AT_data_bit_offset")
        is_bf = bit_size is not None

        bf_width = bit_size.value if bit_size else 0
        bf_bit_offset = 0
        if bit_off_attr:
            bf_bit_offset = bit_off_attr.value % 8

        sf = StructField(
            name=name,
            c_type_name=type_name,
            offset=offset,
            size=type_size,
            is_bitfield=is_bf,
            bitfield_width=bf_width,
            bit_offset=bf_bit_offset,
        )

        # Array detection
        if real_type and real_type.tag == "DW_TAG_array_type":
            elem_die = dwarf_resolve_type(real_type)
            elem_name = dwarf_type_name(elem_die) or ""
            elem_size = dwarf_byte_size(elem_die) if elem_die else 0

            # Get array bound
            count = 0
            for sub in real_type.iter_children():
                if sub.tag == "DW_TAG_subrange_type":
                    ub = sub.attributes.get("DW_AT_upper_bound")
                    cnt = sub.attributes.get("DW_AT_count")
                    if ub is not None:
                        count = ub.value + 1
                    elif cnt is not None:
                        count = cnt.value
                    break

            if count == 0:
                # Flexible array member or zero-length array
                sf.is_flexible_array = True
                sf.element_type_name = elem_name
                sf.element_size = elem_size
                sf.size = 0
            elif elem_name == "char":
                sf.c_type_name = f"char[{count}]"
                sf.size = count
            else:
                sf.is_array = True
                sf.array_size = count
                sf.element_type_name = elem_name
                sf.size = type_size

        fields.append(sf)


# ---------------------------------------------------------------------------
# Build StructInfo/EnumInfo from DWARF data
# ---------------------------------------------------------------------------


def build_enum_infos(ctx):
    enums = []
    seen = set()

    for name, (size, constants) in ctx.raw_enums.items():
        if name in seen:
            continue
        # Skip request/event enum types — their constants are emitted
        # separately by generate_request_const.
        if name.endswith("_requests") or name.endswith("_events"):
            continue
        if name == "__gen_defines":
            continue
        # Skip system enums (e.g. __socket_type from sys/socket.h)
        if not (name.startswith("gr_") or name.startswith("dhcp_")
                or name.startswith("addr_") or name.startswith("conn_")):
            continue
        seen.add(name)

        go_name = c_to_go_name(name)
        go_underlying = dwarf_go_int_type(size)
        go_constants = []
        for cname, cval in constants:
            go_cname = c_enum_const_to_go(name, cname)
            go_constants.append((go_cname, cval))

        ei = EnumInfo(name, go_name, go_underlying, go_constants)
        enums.append(ei)
        KNOWN_ENUMS[name] = go_name

    return enums


def build_struct_infos(ctx):
    structs = []
    seen = set()

    for name, (die, size) in ctx.raw_structs.items():
        if name in seen:
            continue

        # Skip types handled by hand-written Go code
        if name in SPECIAL_TYPE_MAP or name in STRUCT_TYPE_MAP:
            continue
        if name in ("rte_ipv6_addr", "rte_ether_addr", "ip4_net", "ip6_net", "l3_addr"):
            continue
        # Skip *_base structs (flattened via BASE())
        if name.endswith("_base"):
            continue
        # Skip internal/system structs
        if not name.startswith("gr_") and name not in (
            "rte_ether_addr",
            "ip4_net",
            "ip6_net",
        ):
            continue

        seen.add(name)
        fields = extract_struct_fields_dwarf(die)
        si = StructInfo(name, size, fields)
        structs.append(si)
        KNOWN_STRUCTS[name] = si.go_name
        if si.has_flexible_array:
            FLEXIBLE_STRUCTS.add(name)

    return structs


def build_request_infos(ctx):
    infos = []
    for req_name, req_struct, resp_struct, is_stream in ctx.raw_requests:
        type_val = ctx.enum_values.get(req_name, 0)
        if type_val == 0:
            continue
        infos.append(
            RequestInfo(req_name, type_val, req_struct, resp_struct, is_stream)
        )
    return infos


def build_event_infos(ctx):
    infos = []
    for ev_name, payload_struct in ctx.raw_events:
        type_val = ctx.enum_values.get(ev_name, 0)
        if type_val == 0:
            continue
        infos.append(EventInfo(ev_name, type_val, payload_struct))
    return infos


def build_defines(ctx, header_paths):
    """Build define list. Integer values come from DWARF, string values
    from regex (DWARF can't store string initializer values)."""
    result = []

    for name, val in sorted(ctx.defines_int.items()):
        if val > (1 << 32):
            result.append((name, val, "uint64"))
        else:
            result.append((name, val, ""))

    # String defines: read values from source
    for path in header_paths:
        if not os.path.exists(path):
            continue
        with open(path) as f:
            content = f.read()
        for m in STR_DEFINE_RE.finditer(content):
            dname, dval = m.groups()
            result.append((dname, dval, "string"))

    return result


# ---------------------------------------------------------------------------
# Determine which module a struct/enum belongs to
# ---------------------------------------------------------------------------

_source_module_cache = {}


def struct_source_module(name):
    """Map a C name to its module by searching header files."""
    if name in _source_module_cache:
        return _source_module_cache[name]

    # Try naming convention first
    for mod_name, mod in MODULES.items():
        for hdr in mod["headers"]:
            prefix = re.sub(r"\.h$", "", hdr).replace("gr_", "")
            if name.startswith(f"gr_{prefix}"):
                _source_module_cache[name] = mod_name
                return mod_name

    # Search for definition (not just usage) in header content
    for mod_name, mod in MODULES.items():
        for hdr in mod["source_files"]:
            path = find_header(hdr)
            if not path:
                continue
            with open(path) as f:
                content = f.read()
            if f"struct {name} {{" in content or f"#define {name} " in content \
                    or f"\t{name} " in content or f"\t{name}," in content:
                _source_module_cache[name] = mod_name
                return mod_name

    _source_module_cache[name] = None
    return None


def assign_go_types(structs, enums):
    for si in structs:
        for f in si.fields:
            if f.is_flexible_array:
                f.go_name = c_to_go_name(f.name)
                elem = f.element_type_name
                if elem == "char":
                    f.go_type = "string"
                    f.go_elem_type = "string"
                elif elem in ("uint8_t", "unsigned char"):
                    f.go_type = "[]byte"
                    f.go_elem_type = ""
                else:
                    elem_go = go_type_for_c_type(None, elem)
                    if elem_go:
                        f.go_type = f"[]{elem_go}"
                        f.go_elem_type = elem_go
                    else:
                        f.go_type = "[]byte"
                        f.go_elem_type = ""
                continue

            if f.is_array:
                f.go_name = c_to_go_name(f.name)
                elem_go = go_type_for_c_type(None, f.element_type_name)
                if elem_go:
                    f.go_type = f"[{f.array_size}]{elem_go}"
                else:
                    f.go_type = f"[{f.array_size}]byte"
                continue

            f.go_name = c_to_go_name(f.name)

            m = re.match(r"char\[(\d+)\]", f.c_type_name)
            if m:
                f.go_type = "string"
                f.size = int(m.group(1))
                continue

            gt = go_type_for_c_type(None, f.c_type_name)
            if gt:
                f.go_type = gt
            else:
                f.go_type = f"/* TODO: {f.c_type_name} */ [0]byte"

            if f.c_type_name in FLEXIBLE_STRUCTS:
                f.contains_flex = True


def emit(out, template, **kwargs):
    """Write a template string with {key} substitution to out."""
    out.write(template.format(**kwargs))


def field_getter(f):
    """Return the Go expression to read a field from byte slice b."""
    off = f.offset
    if f.is_bitfield:
        mask = (1 << f.bitfield_width) - 1
        return f"{f.go_type}((b[{off}] >> {f.bit_offset}) & {mask})"
    if re.match(r"char\[(\d+)\]", f.c_type_name):
        return f"getString(b, {off}, {f.size})"
    if f.c_type_name in SPECIAL_TYPE_MAP:
        return f"{SPECIAL_TYPE_MAP[f.c_type_name][2]}(b, {off})"
    if f.c_type_name in KNOWN_ENUMS:
        return f"{KNOWN_ENUMS[f.c_type_name]}(getU8(b, {off}))"
    if f.go_type == "bool":
        return f"getBool(b, {off})"
    getter = {1: "getU8", 2: "getU16", 4: "getU32", 8: "getU64"}.get(f.size)
    if getter:
        return f"{f.go_type}({getter}(b, {off}))"
    return None


def field_putter(f):
    """Return the Go statement to write a field into byte slice b."""
    off = f.offset
    if f.is_bitfield:
        mask = (1 << f.bitfield_width) - 1
        return f"b[{off}] |= byte((uint8(s.{f.go_name}) & {mask}) << {f.bit_offset})"
    if re.match(r"char\[(\d+)\]", f.c_type_name):
        return f"putString(b, {off}, {f.size}, s.{f.go_name})"
    if f.c_type_name in SPECIAL_TYPE_MAP:
        return f"{SPECIAL_TYPE_MAP[f.c_type_name][3]}(b, {off}, s.{f.go_name})"
    if f.go_type == "bool":
        return f"putBool(b, {off}, s.{f.go_name})"
    putter = {1: "putU8", 2: "putU16", 4: "putU32", 8: "putU64"}.get(f.size)
    if putter:
        cast = {1: "uint8", 2: "uint16", 4: "uint32", 8: "uint64"}[f.size]
        return f"{putter}(b, {off}, {cast}(s.{f.go_name}))"
    return None


def generate_enum(out, ei):
    emit(out, "type {name} {underlying}\n\n", name=ei.go_name, underlying=ei.underlying)
    out.write("const (\n")
    for go_name, val in ei.constants:
        emit(out, "\t{name} {typ} = {val}\n", name=go_name, typ=ei.go_name, val=val)
    out.write(")\n\n")


def generate_struct(out, si):
    disc = DISCRIMINATED_INFO.get(si.c_name)
    emit(out, "type {name} struct {{", name=si.go_name)
    if si.fields:
        out.write("\n")
        for f in si.fields:
            if f.go_type.startswith("/* TODO"):
                emit(out, "\t// {name} {typ}\n", name=f.go_name, typ=f.go_type)
            elif f.is_flexible_array and disc and f.go_name == disc["go_field"]:
                emit(out, "\t{name} any\n", name=f.go_name)
            else:
                emit(out, "\t{name} {typ}\n", name=f.go_name, typ=f.go_type)
    out.write("}\n\n")


def generate_unmarshal(out, si):
    emit(
        out,
        """\
func (s *{name}) unmarshal(b []byte) error {{
\tif len(b) < {size} {{
\t\treturn fmt.Errorf("{name}: buffer too short: %d < {size}", len(b))
\t}}
""",
        name=si.go_name,
        size=si.size,
    )

    for f in si.fields:
        if f.go_type.startswith("/* TODO"):
            continue
        if f.is_flexible_array:
            _emit_flex_unmarshal(out, si, f)
            continue

        # Struct types with their own unmarshal
        if f.c_type_name in STRUCT_TYPE_MAP:
            go_t = STRUCT_TYPE_MAP[f.c_type_name]
            if go_t == "IPv4Net":
                emit(
                    out,
                    "\ts.{n} = getIPv4Net(b, {o}, {o4})\n",
                    n=f.go_name,
                    o=f.offset,
                    o4=f.offset + 4,
                )
            elif go_t == "IPv6Net":
                emit(
                    out,
                    "\ts.{n} = getIPv6Net(b, {o}, {o16})\n",
                    n=f.go_name,
                    o=f.offset,
                    o16=f.offset + 16,
                )
            continue
        if f.c_type_name in KNOWN_STRUCTS:
            sl = (
                f"b[{f.offset}:]"
                if f.contains_flex
                else f"b[{f.offset}:{f.offset + f.size}]"
            )
            emit(
                out,
                """\
\tif err := s.{n}.unmarshal({sl}); err != nil {{
\t\treturn err
\t}}
""",
                n=f.go_name,
                sl=sl,
            )
            continue
        if f.is_array:
            elem_go = KNOWN_STRUCTS.get(f.element_type_name, "")
            elem_size = f.size // f.array_size if f.array_size > 0 else 0
            if elem_go and elem_size > 0:
                emit(
                    out,
                    """\
\tfor i := range s.{n} {{
\t\toff := {o} + i*{esz}
\t\tif err := s.{n}[i].unmarshal(b[off:off+{esz}]); err != nil {{
\t\t\treturn err
\t\t}}
\t}}
""",
                    n=f.go_name,
                    o=f.offset,
                    esz=elem_size,
                )
            continue

        # Scalar fields
        expr = field_getter(f)
        if expr:
            emit(out, "\ts.{n} = {expr}\n", n=f.go_name, expr=expr)

    out.write("\treturn nil\n}\n\n")


def _emit_flex_unmarshal(out, si, f):
    disc = DISCRIMINATED_INFO.get(si.c_name)
    if disc and f.go_name == disc["go_field"]:
        emit(
            out,
            "\tif len(b) > {sz} {{\n\t\tinfo := b[{sz}:]\n\t\tswitch s.{d} {{\n",
            sz=si.size,
            d=disc["discriminator"],
        )
        for const_name, info_type in disc["mapping"].items():
            emit(
                out,
                """\
\t\tcase {c}:
\t\t\tvar v {t}
\t\t\tif err := v.unmarshal(info); err != nil {{
\t\t\t\treturn err
\t\t\t}}
\t\t\ts.{n} = &v
""",
                c=const_name,
                t=info_type,
                n=f.go_name,
            )
        out.write("\t\t}\n\t}\n")
    elif f.go_elem_type == "string":
        emit(
            out,
            """\
\tif len(b) > {sz} {{
\t\ts.{n} = getString(b, {sz}, len(b)-{sz})
\t}}
""",
            sz=si.size,
            n=f.go_name,
        )
    elif f.go_elem_type == "netip.Addr" and f.element_type_name == "rte_ipv6_addr":
        emit(
            out,
            """\
\tfor off := {sz}; off+16 <= len(b); off += 16 {{
\t\ts.{n} = append(s.{n}, getIPv6(b, off))
\t}}
""",
            sz=si.size,
            n=f.go_name,
        )
    elif f.element_size > 0 and f.go_elem_type in KNOWN_STRUCTS.values():
        emit(
            out,
            """\
\tfor off := {sz}; off+{esz} <= len(b); off += {esz} {{
\t\tvar elem {t}
\t\tif err := elem.unmarshal(b[off:off+{esz}]); err != nil {{
\t\t\treturn err
\t\t}}
\t\ts.{n} = append(s.{n}, elem)
\t}}
""",
            sz=si.size,
            esz=f.element_size,
            t=f.go_elem_type,
            n=f.go_name,
        )
    elif not f.go_elem_type:
        emit(
            out,
            """\
\tif len(b) > {sz} {{
\t\ts.{n} = make([]byte, len(b)-{sz})
\t\tcopy(s.{n}, b[{sz}:])
\t}}
""",
            sz=si.size,
            n=f.go_name,
        )


def generate_marshal(out, si):
    emit(
        out,
        """\
func (s *{name}) marshal() []byte {{
\tb := make([]byte, {size})
""",
        name=si.go_name,
        size=si.size,
    )

    for f in si.fields:
        if f.go_type.startswith("/* TODO") or f.is_flexible_array:
            continue

        if f.c_type_name in STRUCT_TYPE_MAP:
            go_t = STRUCT_TYPE_MAP[f.c_type_name]
            if go_t == "IPv4Net":
                emit(
                    out,
                    "\tputIPv4Net(b, {o}, {o4}, s.{n})\n",
                    o=f.offset,
                    o4=f.offset + 4,
                    n=f.go_name,
                )
            elif go_t == "IPv6Net":
                emit(
                    out,
                    "\tputIPv6Net(b, {o}, {o16}, s.{n})\n",
                    o=f.offset,
                    o16=f.offset + 16,
                    n=f.go_name,
                )
            continue
        if f.c_type_name in KNOWN_STRUCTS:
            if f.contains_flex:
                emit(
                    out,
                    """\
\t{{
\t\td := s.{n}.marshal()
\t\tcopy(b[{o}:], d[:min(len(d), len(b)-{o})])
\t\tif len(d) > {sz} {{
\t\t\tb = append(b, d[{sz}:]...)
\t\t}}
\t}}
""",
                    n=f.go_name,
                    o=f.offset,
                    sz=f.size,
                )
            else:
                emit(out, "\tcopy(b[{o}:], s.{n}.marshal())\n", o=f.offset, n=f.go_name)
            continue
        if f.is_array:
            continue

        stmt = field_putter(f)
        if stmt:
            emit(out, "\t{stmt}\n", stmt=stmt)

    if si.has_flexible_array:
        for f in si.fields:
            if f.is_flexible_array:
                _emit_flex_marshal(out, si, f)

    out.write("\treturn b\n}\n\n")


def _emit_flex_marshal(out, si, f):
    disc = DISCRIMINATED_INFO.get(si.c_name)
    if disc and f.go_name == disc["go_field"]:
        emit(
            out,
            """\
\tif s.{n} != nil {{
\t\tif m, ok := s.{n}.(marshaler); ok {{
\t\t\tb = append(b, m.marshal()...)
\t\t}}
\t}}
""",
            n=f.go_name,
        )
    elif f.go_elem_type == "string":
        emit(
            out, "\tb = append(b, []byte(s.{n})...)\n\tb = append(b, 0)\n", n=f.go_name
        )
    elif f.go_elem_type == "netip.Addr" and f.element_type_name == "rte_ipv6_addr":
        emit(
            out,
            """\
\tfor _, addr := range s.{n} {{
\t\ta16 := addr.As16()
\t\tb = append(b, a16[:]...)
\t}}
""",
            n=f.go_name,
        )
    elif f.element_size > 0 and f.go_elem_type in KNOWN_STRUCTS.values():
        emit(
            out,
            """\
\tfor i := range s.{n} {{
\t\tb = append(b, s.{n}[i].marshal()...)
\t}}
""",
            n=f.go_name,
        )
    elif not f.go_elem_type:
        emit(out, "\tb = append(b, s.{n}...)\n", n=f.go_name)


def generate_defines(out, defines):
    if not defines:
        return
    out.write("// Constants from #define macros.\nconst (\n")
    for name, val, go_type in defines:
        go_name = c_to_go_name(name)
        if go_type == "string":
            emit(out, '\t{n} = "{v}"\n', n=go_name, v=val)
        elif go_type == "uint64":
            emit(out, "\t{n} uint64 = 0x{v:x}\n", n=go_name, v=val)
        elif isinstance(val, int) and val > 0xFFFF:
            emit(out, "\t{n} = 0x{v:x}\n", n=go_name, v=val)
        else:
            emit(out, "\t{n} = {v}\n", n=go_name, v=val)
    out.write(")\n\n")


def generate_request_const(out, req_infos, event_infos):
    if req_infos:
        out.write("// Request type constants.\nconst (\n")
        for ri in req_infos:
            go_name = "gr" + c_to_go_name(ri.name)
            ri.go_const = go_name[0].lower() + go_name[1:]
            emit(out, "\t{n} uint32 = 0x{v:08x}\n", n=ri.go_const, v=ri.type_val)
        out.write(")\n\n")
    if event_infos:
        out.write("// Event type constants.\nconst (\n")
        for ei in event_infos:
            ei.go_const = c_to_go_name(ei.name)
            emit(out, "\t{n} uint32 = 0x{v:08x}\n", n=ei.go_const, v=ei.type_val)
        out.write(")\n\n")


def generate_api_methods(out, req_infos):
    for ri in req_infos:
        req_go = KNOWN_STRUCTS.get(ri.req_struct)
        resp_go = KNOWN_STRUCTS.get(ri.resp_struct)
        if not req_go and ri.req_struct != "gr_empty":
            continue
        if not resp_go and ri.resp_struct != "gr_empty":
            continue

        method = c_to_go_name(ri.name)
        has_req = ri.req_struct != "gr_empty"
        has_resp = ri.resp_struct != "gr_empty"

        if ri.is_stream:
            if has_req:
                emit(
                    out,
                    """\
func (c *Client) {m}(req *{rq}) iter.Seq2[*{rp}, error] {{
\treturn streamIter[{rp}](c, {k}, req.marshal())
}}

""",
                    m=method,
                    rq=req_go,
                    rp=resp_go,
                    k=ri.go_const,
                )
            else:
                emit(
                    out,
                    """\
func (c *Client) {m}() iter.Seq2[*{rp}, error] {{
\treturn streamIter[{rp}](c, {k}, nil)
}}

""",
                    m=method,
                    rp=resp_go,
                    k=ri.go_const,
                )
        elif not has_resp:
            if has_req:
                emit(
                    out,
                    """\
func (c *Client) {m}(req *{rq}) error {{
\treturn c.sendOnly({k}, req.marshal())
}}

""",
                    m=method,
                    rq=req_go,
                    k=ri.go_const,
                )
            else:
                emit(
                    out,
                    """\
func (c *Client) {m}() error {{
\treturn c.sendOnly({k}, nil)
}}

""",
                    m=method,
                    k=ri.go_const,
                )
        else:
            payload = "req.marshal()" if has_req else "nil"
            sig = f"(req *{req_go})" if has_req else "()"
            emit(
                out,
                """\
func (c *Client) {m}{sig} (*{rp}, error) {{
\tdata, err := c.sendRecv({k}, {p})
\tif err != nil {{
\t\treturn nil, err
\t}}
\tresp := new({rp})
\tif data != nil {{
\t\tif err := resp.unmarshal(data); err != nil {{
\t\t\treturn nil, err
\t\t}}
\t}}
\treturn resp, nil
}}

""",
                m=method,
                sig=sig,
                rp=resp_go,
                k=ri.go_const,
                p=payload,
            )


def generate_event_decoders(out, event_infos):
    out.write("func init() {\n")
    for ei in event_infos:
        payload_go = KNOWN_STRUCTS.get(ei.payload_struct)
        if not payload_go:
            continue
        emit(
            out,
            """\
\tregisterEventDecoder({k}, func(b []byte) (any, error) {{
\t\tv := new({t})
\t\tif err := v.unmarshal(b); err != nil {{
\t\t\treturn nil, err
\t\t}}
\t\treturn v, nil
\t}})
""",
            k=ei.go_const,
            t=payload_go,
        )
    out.write("}\n\n")


def needs_import(content, pkg):
    if pkg == "fmt":
        return "fmt." in content
    if pkg == "iter":
        return "iter.Seq2" in content
    if pkg == "net/netip":
        return "netip." in content
    return False


# ---------------------------------------------------------------------------
# Module generation
# ---------------------------------------------------------------------------


def generate_module(ctx, module_name):
    enums = ctx.enums_by_mod.get(module_name, [])
    structs = ctx.structs_by_mod.get(module_name, [])
    req_infos = ctx.reqs_by_mod.get(module_name, [])
    event_infos = ctx.events_by_mod.get(module_name, [])
    defines = ctx.defines_by_mod.get(module_name, [])

    assign_go_types(structs, enums)
    for si in structs:
        si.update_flex()

    body = io.StringIO()

    for ei in enums:
        generate_enum(body, ei)

    generate_defines(body, defines)

    if module_name == "api":
        ev_sz = ctx.type_sizes.get("gr_api_event", 16)
        req_sz = ctx.type_sizes.get("gr_api_request", 12)
        resp_sz = ctx.type_sizes.get("gr_api_response", 12)
        body.write("const (\n")
        body.write(f"\teventHeaderSize = {ev_sz}\n")
        body.write(f"\treqHeaderSize = {req_sz}\n")
        body.write(f"\trespHeaderSize = {resp_sz}\n\n")
        body.write(")\n\n")

    for si in structs:
        generate_struct(body, si)
        generate_unmarshal(body, si)
        generate_marshal(body, si)

    generate_request_const(body, req_infos, event_infos)
    generate_api_methods(body, req_infos)

    if event_infos:
        generate_event_decoders(body, event_infos)

    body_str = body.getvalue()

    buf = io.StringIO()
    buf.write(HEADER)
    buf.write("package grout\n\n")

    imports = []
    if needs_import(body_str, "fmt"):
        imports.append('"fmt"')
    if needs_import(body_str, "iter"):
        imports.append('"iter"')
    if needs_import(body_str, "net/netip"):
        imports.append('"net/netip"')

    if imports:
        if len(imports) == 1:
            buf.write(f"import {imports[0]}\n\n")
        else:
            buf.write("import (\n")
            for imp in imports:
                buf.write(f"\t{imp}\n")
            buf.write(")\n\n")

    buf.write(body_str)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o",
        "--output-dir",
        required=True,
        help="Directory to write generated Go files into",
    )
    parser.add_argument(
        "-d",
        "--diff-dir",
        help="Compare generated files against this directory and fail if "
        "any differ (for build-time staleness check)",
    )
    parser.add_argument(
        "-s",
        "--stamp",
        help="Touch this file on success (for meson custom_target output)",
    )
    parser.add_argument(
        "--cc",
        required=True,
        help="C compiler command (space-separated, as passed by meson)",
    )
    parser.add_argument(
        "headers",
        nargs="+",
        help="API header files (as passed by meson)",
    )
    args = parser.parse_args()

    gofmt = shutil.which("gofmt")
    if not gofmt:
        print("error: gofmt not found", file=sys.stderr)
        return 1

    build_modules(args.headers)
    ctx = Ctx()

    print("Compiling API headers...", file=sys.stderr)
    obj_path = compile_headers(args.cc, args.headers)
    try:
        print("Extracting DWARF info...", file=sys.stderr)
        extract_all_from_dwarf(ctx, obj_path)
    finally:
        os.unlink(obj_path)

    if "cpu_set_t" in ctx.type_sizes:
        entry = SPECIAL_TYPE_MAP["cpu_set_t"]
        SPECIAL_TYPE_MAP["cpu_set_t"] = (
            entry[0], ctx.type_sizes["cpu_set_t"], entry[2], entry[3],
        )

    all_enums = build_enum_infos(ctx)
    all_structs = build_struct_infos(ctx)
    all_reqs = build_request_infos(ctx)
    all_events = build_event_infos(ctx)
    all_defines = build_defines(ctx, args.headers)

    for ei in all_enums:
        ctx.enums_by_mod.setdefault(
            struct_source_module(ei.c_name) or "types", []
        ).append(ei)
    for si in all_structs:
        ctx.structs_by_mod.setdefault(
            struct_source_module(si.c_name) or "types", []
        ).append(si)
    for ri in all_reqs:
        ctx.reqs_by_mod.setdefault(
            struct_source_module(ri.name) or "api", []
        ).append(ri)
    for ei in all_events:
        ctx.events_by_mod.setdefault(
            struct_source_module(ei.name) or "api", []
        ).append(ei)
    for name, val, go_type in all_defines:
        ctx.defines_by_mod.setdefault(
            struct_source_module(name) or "api", []
        ).append((name, val, go_type))

    output_dir = args.output_dir
    os.makedirs(output_dir, exist_ok=True)

    for module_name in MODULES:
        filename = f"gen_{module_name}.go"
        filepath = os.path.join(output_dir, filename)
        content = generate_module(ctx, module_name)
        result = subprocess.run(
            [gofmt],
            input=content,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            print(
                f"error: gofmt failed on {filename}:\n{result.stderr}", file=sys.stderr
            )
            return 1
        with open(filepath, "w") as f:
            f.write(result.stdout)
        print(f"  wrote {filepath}", file=sys.stderr)

    if args.diff_dir:
        stale = []
        for module_name in MODULES:
            filename = f"gen_{module_name}.go"
            gen_path = os.path.join(output_dir, filename)
            src_path = os.path.join(args.diff_dir, filename)

            with open(gen_path) as f:
                generated = f.read()

            if os.path.exists(src_path):
                with open(src_path) as f:
                    existing = f.read()
                if existing != generated:
                    stale.append(filename)
                    diff = difflib.unified_diff(
                        existing.splitlines(keepends=True),
                        generated.splitlines(keepends=True),
                        fromfile=f"a/go/{filename}",
                        tofile=f"b/go/{filename}",
                    )
                    sys.stderr.writelines(diff)
            else:
                stale.append(filename)
                print(f"  {src_path}: missing", file=sys.stderr)

        if stale:
            print(
                f"\nStale generated files: {', '.join(stale)}",
                file=sys.stderr,
            )
            print("Run 'ninja update-go' to regenerate.", file=sys.stderr)
            return 1
        print("Generated files are up to date.", file=sys.stderr)

    if args.stamp:
        with open(args.stamp, "w") as f:
            f.write("")

    return 0


if __name__ == "__main__":
    sys.exit(main())
