// Code generated by devtools/gen-go.py; DO NOT EDIT.

package grout

import (
	"fmt"
	"iter"
)

type IfaceType uint8

const (
	IfaceTypeUndef  IfaceType = 0
	IfaceTypeVRF    IfaceType = 1
	IfaceTypePort   IfaceType = 2
	IfaceTypeVLAN   IfaceType = 3
	IfaceTypeIPIP   IfaceType = 4
	IfaceTypeBond   IfaceType = 5
	IfaceTypeBridge IfaceType = 6
	IfaceTypeVXLAN  IfaceType = 7
	IfaceTypeCount  IfaceType = 8
)

type IfaceFlags uint16

const (
	IfaceFUp          IfaceFlags = 1
	IfaceFPromisc     IfaceFlags = 2
	IfaceFPacketTrace IfaceFlags = 4
	IfaceFSNATStatic  IfaceFlags = 8
	IfaceFSNATDynamic IfaceFlags = 16
)

type IfaceState uint16

const (
	IfaceSRunning      IfaceState = 1
	IfaceSPromiscFixed IfaceState = 2
	IfaceSAllmulti     IfaceState = 4
)

type IfaceMode uint8

const (
	IfaceModeVRF    IfaceMode = 0
	IfaceModeXc     IfaceMode = 1
	IfaceModeBond   IfaceMode = 2
	IfaceModeBridge IfaceMode = 3
	IfaceModeCount  IfaceMode = 4
)

type BondMode uint8

const (
	BondModeActiveBackup BondMode = 1
	BondModeLACP         BondMode = 2
)

type BondAlgo uint8

const (
	BondAlgoRSS  BondAlgo = 1
	BondAlgoL2   BondAlgo = 2
	BondAlgoL3L4 BondAlgo = 3
)

type StatsFlags uint16

const (
	StatsFSW   StatsFlags = 1
	StatsFHW   StatsFlags = 2
	StatsFZero StatsFlags = 4
)

// Constants from #define macros.
const (
	BondSetAlgo        uint64 = 0x800000000
	BondSetMAC         uint64 = 0x400000000
	BondSetMode               = 0x100000000
	BondSetPrimary     uint64 = 0x200000000
	IfaceIDUndef              = 0
	IfaceSetDescr             = 32
	IfaceSetDomain            = 16
	IfaceSetFlags             = 1
	IfaceSetMTU               = 2
	IfaceSetName              = 4
	IfaceSetVRF               = 8
	MaxIfaces                 = 1024
	PacketTraceBatch          = 32
	PortDevargsSize           = 128
	PortDriverNameSize        = 32
	PortSetMAC         uint64 = 0x800000000
	PortSetNRxqs              = 0x100000000
	PortSetNTxqs       uint64 = 0x200000000
	PortSetQSize       uint64 = 0x400000000
	VLANSetMAC         uint64 = 0x400000000
	VLANSetParent             = 0x100000000
	VLANSetVLAN        uint64 = 0x200000000
	VRFDefaultID              = 1
	VRFSetFIB                 = 0x100000000
	VRFSetMAC          uint64 = 0x200000000
	DefaultVRFName            = "main"
)

type Iface struct {
	ID          uint16
	Type        IfaceType
	Mode        IfaceMode
	Flags       IfaceFlags
	State       IfaceState
	MTU         uint16
	VRFID       uint16
	DomainID    uint16
	Speed       uint32
	Name        string
	Description string
	Info        any
}

func (s *Iface) unmarshal(b []byte) error {
	if len(b) < 292 {
		return fmt.Errorf("Iface: buffer too short: %d < 292", len(b))
	}
	s.ID = uint16(getU16(b, 0))
	s.Type = IfaceType(getU8(b, 2))
	s.Mode = IfaceMode(getU8(b, 3))
	s.Flags = IfaceFlags(getU8(b, 4))
	s.State = IfaceState(getU8(b, 6))
	s.MTU = uint16(getU16(b, 8))
	s.VRFID = uint16(getU16(b, 10))
	s.DomainID = uint16(getU16(b, 12))
	s.Speed = uint32(getU32(b, 16))
	s.Name = getString(b, 20, 16)
	s.Description = getString(b, 36, 256)
	if len(b) > 292 {
		info := b[292:]
		switch s.Type {
		case IfaceTypePort:
			var v IfaceInfoPort
			if err := v.unmarshal(info); err != nil {
				return err
			}
			s.Info = &v
		case IfaceTypeVRF:
			var v IfaceInfoVRF
			if err := v.unmarshal(info); err != nil {
				return err
			}
			s.Info = &v
		case IfaceTypeVLAN:
			var v IfaceInfoVLAN
			if err := v.unmarshal(info); err != nil {
				return err
			}
			s.Info = &v
		case IfaceTypeBond:
			var v IfaceInfoBond
			if err := v.unmarshal(info); err != nil {
				return err
			}
			s.Info = &v
		case IfaceTypeBridge:
			var v IfaceInfoBridge
			if err := v.unmarshal(info); err != nil {
				return err
			}
			s.Info = &v
		case IfaceTypeIPIP:
			var v IfaceInfoIPIP
			if err := v.unmarshal(info); err != nil {
				return err
			}
			s.Info = &v
		case IfaceTypeVXLAN:
			var v IfaceInfoVXLAN
			if err := v.unmarshal(info); err != nil {
				return err
			}
			s.Info = &v
		}
	}
	return nil
}

func (s *Iface) marshal() []byte {
	b := make([]byte, 292)
	putU16(b, 0, uint16(s.ID))
	putU8(b, 2, uint8(s.Type))
	putU8(b, 3, uint8(s.Mode))
	putU16(b, 4, uint16(s.Flags))
	putU16(b, 6, uint16(s.State))
	putU16(b, 8, uint16(s.MTU))
	putU16(b, 10, uint16(s.VRFID))
	putU16(b, 12, uint16(s.DomainID))
	putU32(b, 16, uint32(s.Speed))
	putString(b, 20, 16, s.Name)
	putString(b, 36, 256, s.Description)
	if s.Info != nil {
		if m, ok := s.Info.(marshaler); ok {
			b = append(b, m.marshal()...)
		}
	}
	return b
}

type IfaceInfoPort struct {
	NRXQ       uint16
	NTXQ       uint16
	RXQSize    uint16
	TXQSize    uint16
	MAC        EtherAddr
	Devargs    string
	DriverName string
}

func (s *IfaceInfoPort) unmarshal(b []byte) error {
	if len(b) < 174 {
		return fmt.Errorf("IfaceInfoPort: buffer too short: %d < 174", len(b))
	}
	s.NRXQ = uint16(getU16(b, 0))
	s.NTXQ = uint16(getU16(b, 2))
	s.RXQSize = uint16(getU16(b, 4))
	s.TXQSize = uint16(getU16(b, 6))
	s.MAC = getEther(b, 8)
	s.Devargs = getString(b, 14, 128)
	s.DriverName = getString(b, 142, 32)
	return nil
}

func (s *IfaceInfoPort) marshal() []byte {
	b := make([]byte, 174)
	putU16(b, 0, uint16(s.NRXQ))
	putU16(b, 2, uint16(s.NTXQ))
	putU16(b, 4, uint16(s.RXQSize))
	putU16(b, 6, uint16(s.TXQSize))
	putEther(b, 8, s.MAC)
	putString(b, 14, 128, s.Devargs)
	putString(b, 142, 32, s.DriverName)
	return b
}

type IfaceInfoVRFFIB struct {
	MaxRoutes uint32
	NumTbl8   uint32
}

func (s *IfaceInfoVRFFIB) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("IfaceInfoVRFFIB: buffer too short: %d < 8", len(b))
	}
	s.MaxRoutes = uint32(getU32(b, 0))
	s.NumTbl8 = uint32(getU32(b, 4))
	return nil
}

func (s *IfaceInfoVRFFIB) marshal() []byte {
	b := make([]byte, 8)
	putU32(b, 0, uint32(s.MaxRoutes))
	putU32(b, 4, uint32(s.NumTbl8))
	return b
}

type IfaceInfoVRF struct {
	Ipv4 IfaceInfoVRFFIB
	Ipv6 IfaceInfoVRFFIB
	MAC  EtherAddr
}

func (s *IfaceInfoVRF) unmarshal(b []byte) error {
	if len(b) < 24 {
		return fmt.Errorf("IfaceInfoVRF: buffer too short: %d < 24", len(b))
	}
	if err := s.Ipv4.unmarshal(b[0:8]); err != nil {
		return err
	}
	if err := s.Ipv6.unmarshal(b[8:16]); err != nil {
		return err
	}
	s.MAC = getEther(b, 16)
	return nil
}

func (s *IfaceInfoVRF) marshal() []byte {
	b := make([]byte, 24)
	copy(b[0:], s.Ipv4.marshal())
	copy(b[8:], s.Ipv6.marshal())
	putEther(b, 16, s.MAC)
	return b
}

type IfaceInfoVLAN struct {
	ParentID uint16
	VLANID   uint16
	MAC      EtherAddr
}

func (s *IfaceInfoVLAN) unmarshal(b []byte) error {
	if len(b) < 10 {
		return fmt.Errorf("IfaceInfoVLAN: buffer too short: %d < 10", len(b))
	}
	s.ParentID = uint16(getU16(b, 0))
	s.VLANID = uint16(getU16(b, 2))
	s.MAC = getEther(b, 4)
	return nil
}

func (s *IfaceInfoVLAN) marshal() []byte {
	b := make([]byte, 10)
	putU16(b, 0, uint16(s.ParentID))
	putU16(b, 2, uint16(s.VLANID))
	putEther(b, 4, s.MAC)
	return b
}

type BondMember struct {
	IfaceID uint16
	Active  bool
}

func (s *BondMember) unmarshal(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("BondMember: buffer too short: %d < 4", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.Active = getBool(b, 2)
	return nil
}

func (s *BondMember) marshal() []byte {
	b := make([]byte, 4)
	putU16(b, 0, uint16(s.IfaceID))
	putBool(b, 2, s.Active)
	return b
}

type IfaceInfoBond struct {
	Mode          BondMode
	Algo          BondAlgo
	MAC           EtherAddr
	PrimaryMember uint8
	NMembers      uint8
	Members       [8]BondMember
}

func (s *IfaceInfoBond) unmarshal(b []byte) error {
	if len(b) < 42 {
		return fmt.Errorf("IfaceInfoBond: buffer too short: %d < 42", len(b))
	}
	s.Mode = BondMode(getU8(b, 0))
	s.Algo = BondAlgo(getU8(b, 1))
	s.MAC = getEther(b, 2)
	s.PrimaryMember = uint8(getU8(b, 8))
	s.NMembers = uint8(getU8(b, 9))
	return nil
}

func (s *IfaceInfoBond) marshal() []byte {
	b := make([]byte, 42)
	putU8(b, 0, uint8(s.Mode))
	putU8(b, 1, uint8(s.Algo))
	putEther(b, 2, s.MAC)
	putU8(b, 8, uint8(s.PrimaryMember))
	putU8(b, 9, uint8(s.NMembers))
	return b
}

type PortRXQMap struct {
	IfaceID uint16
	RXQID   uint16
	CPUID   uint16
	Enabled uint16
}

func (s *PortRXQMap) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("PortRXQMap: buffer too short: %d < 8", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.RXQID = uint16(getU16(b, 2))
	s.CPUID = uint16(getU16(b, 4))
	s.Enabled = uint16(getU16(b, 6))
	return nil
}

func (s *PortRXQMap) marshal() []byte {
	b := make([]byte, 8)
	putU16(b, 0, uint16(s.IfaceID))
	putU16(b, 2, uint16(s.RXQID))
	putU16(b, 4, uint16(s.CPUID))
	putU16(b, 6, uint16(s.Enabled))
	return b
}

type Stat struct {
	Name      string
	TopoOrder uint64
	Packets   uint64
	Batches   uint64
	Cycles    uint64
}

func (s *Stat) unmarshal(b []byte) error {
	if len(b) < 96 {
		return fmt.Errorf("Stat: buffer too short: %d < 96", len(b))
	}
	s.Name = getString(b, 0, 64)
	s.TopoOrder = uint64(getU64(b, 64))
	s.Packets = uint64(getU64(b, 72))
	s.Batches = uint64(getU64(b, 80))
	s.Cycles = uint64(getU64(b, 88))
	return nil
}

func (s *Stat) marshal() []byte {
	b := make([]byte, 96)
	putString(b, 0, 64, s.Name)
	putU64(b, 64, uint64(s.TopoOrder))
	putU64(b, 72, uint64(s.Packets))
	putU64(b, 80, uint64(s.Batches))
	putU64(b, 88, uint64(s.Cycles))
	return b
}

type IfaceAddReq struct {
	Iface Iface
}

func (s *IfaceAddReq) unmarshal(b []byte) error {
	if len(b) < 292 {
		return fmt.Errorf("IfaceAddReq: buffer too short: %d < 292", len(b))
	}
	if err := s.Iface.unmarshal(b[0:]); err != nil {
		return err
	}
	return nil
}

func (s *IfaceAddReq) marshal() []byte {
	b := make([]byte, 292)
	{
		d := s.Iface.marshal()
		copy(b[0:], d[:min(len(d), len(b)-0)])
		if len(d) > 292 {
			b = append(b, d[292:]...)
		}
	}
	return b
}

type IfaceAddResp struct {
	IfaceID uint16
}

func (s *IfaceAddResp) unmarshal(b []byte) error {
	if len(b) < 2 {
		return fmt.Errorf("IfaceAddResp: buffer too short: %d < 2", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	return nil
}

func (s *IfaceAddResp) marshal() []byte {
	b := make([]byte, 2)
	putU16(b, 0, uint16(s.IfaceID))
	return b
}

type IfaceDelReq struct {
	IfaceID uint16
}

func (s *IfaceDelReq) unmarshal(b []byte) error {
	if len(b) < 2 {
		return fmt.Errorf("IfaceDelReq: buffer too short: %d < 2", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	return nil
}

func (s *IfaceDelReq) marshal() []byte {
	b := make([]byte, 2)
	putU16(b, 0, uint16(s.IfaceID))
	return b
}

type IfaceGetReq struct {
	IfaceID uint16
	Name    string
}

func (s *IfaceGetReq) unmarshal(b []byte) error {
	if len(b) < 18 {
		return fmt.Errorf("IfaceGetReq: buffer too short: %d < 18", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.Name = getString(b, 2, 16)
	return nil
}

func (s *IfaceGetReq) marshal() []byte {
	b := make([]byte, 18)
	putU16(b, 0, uint16(s.IfaceID))
	putString(b, 2, 16, s.Name)
	return b
}

type IfaceGetResp struct {
	Iface Iface
}

func (s *IfaceGetResp) unmarshal(b []byte) error {
	if len(b) < 292 {
		return fmt.Errorf("IfaceGetResp: buffer too short: %d < 292", len(b))
	}
	if err := s.Iface.unmarshal(b[0:]); err != nil {
		return err
	}
	return nil
}

func (s *IfaceGetResp) marshal() []byte {
	b := make([]byte, 292)
	{
		d := s.Iface.marshal()
		copy(b[0:], d[:min(len(d), len(b)-0)])
		if len(d) > 292 {
			b = append(b, d[292:]...)
		}
	}
	return b
}

type IfaceListReq struct {
	Type IfaceType
}

func (s *IfaceListReq) unmarshal(b []byte) error {
	if len(b) < 1 {
		return fmt.Errorf("IfaceListReq: buffer too short: %d < 1", len(b))
	}
	s.Type = IfaceType(getU8(b, 0))
	return nil
}

func (s *IfaceListReq) marshal() []byte {
	b := make([]byte, 1)
	putU8(b, 0, uint8(s.Type))
	return b
}

type IfaceMACAddReq struct {
	IfaceID uint16
	MAC     EtherAddr
}

func (s *IfaceMACAddReq) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("IfaceMACAddReq: buffer too short: %d < 8", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.MAC = getEther(b, 2)
	return nil
}

func (s *IfaceMACAddReq) marshal() []byte {
	b := make([]byte, 8)
	putU16(b, 0, uint16(s.IfaceID))
	putEther(b, 2, s.MAC)
	return b
}

type IfaceMACDelReq struct {
	IfaceID uint16
	MAC     EtherAddr
}

func (s *IfaceMACDelReq) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("IfaceMACDelReq: buffer too short: %d < 8", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.MAC = getEther(b, 2)
	return nil
}

func (s *IfaceMACDelReq) marshal() []byte {
	b := make([]byte, 8)
	putU16(b, 0, uint16(s.IfaceID))
	putEther(b, 2, s.MAC)
	return b
}

type IfaceMACListReq struct {
	IfaceID uint16
}

func (s *IfaceMACListReq) unmarshal(b []byte) error {
	if len(b) < 2 {
		return fmt.Errorf("IfaceMACListReq: buffer too short: %d < 2", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	return nil
}

func (s *IfaceMACListReq) marshal() []byte {
	b := make([]byte, 2)
	putU16(b, 0, uint16(s.IfaceID))
	return b
}

type IfaceMAC struct {
	IfaceID uint16
	Refcnt  uint16
	Primary bool
	MAC     EtherAddr
}

func (s *IfaceMAC) unmarshal(b []byte) error {
	if len(b) < 12 {
		return fmt.Errorf("IfaceMAC: buffer too short: %d < 12", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.Refcnt = uint16(getU16(b, 2))
	s.Primary = getBool(b, 4)
	s.MAC = getEther(b, 6)
	return nil
}

func (s *IfaceMAC) marshal() []byte {
	b := make([]byte, 12)
	putU16(b, 0, uint16(s.IfaceID))
	putU16(b, 2, uint16(s.Refcnt))
	putBool(b, 4, s.Primary)
	putEther(b, 6, s.MAC)
	return b
}

type IfaceMACSetReq struct {
	IfaceID uint16
	MAC     EtherAddr
}

func (s *IfaceMACSetReq) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("IfaceMACSetReq: buffer too short: %d < 8", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.MAC = getEther(b, 2)
	return nil
}

func (s *IfaceMACSetReq) marshal() []byte {
	b := make([]byte, 8)
	putU16(b, 0, uint16(s.IfaceID))
	putEther(b, 2, s.MAC)
	return b
}

type IfaceSetReq struct {
	SetAttrs uint64
	Iface    Iface
}

func (s *IfaceSetReq) unmarshal(b []byte) error {
	if len(b) < 304 {
		return fmt.Errorf("IfaceSetReq: buffer too short: %d < 304", len(b))
	}
	s.SetAttrs = uint64(getU64(b, 0))
	if err := s.Iface.unmarshal(b[8:]); err != nil {
		return err
	}
	return nil
}

func (s *IfaceSetReq) marshal() []byte {
	b := make([]byte, 304)
	putU64(b, 0, uint64(s.SetAttrs))
	{
		d := s.Iface.marshal()
		copy(b[8:], d[:min(len(d), len(b)-8)])
		if len(d) > 292 {
			b = append(b, d[292:]...)
		}
	}
	return b
}

type IfaceStats struct {
	IfaceID     uint16
	RXPackets   uint64
	RXBytes     uint64
	RXDrops     uint64
	TXPackets   uint64
	TXBytes     uint64
	TXErrors    uint64
	CpRXPackets uint64
	CpRXBytes   uint64
	CpTXPackets uint64
	CpTXBytes   uint64
}

func (s *IfaceStats) unmarshal(b []byte) error {
	if len(b) < 88 {
		return fmt.Errorf("IfaceStats: buffer too short: %d < 88", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.RXPackets = uint64(getU64(b, 8))
	s.RXBytes = uint64(getU64(b, 16))
	s.RXDrops = uint64(getU64(b, 24))
	s.TXPackets = uint64(getU64(b, 32))
	s.TXBytes = uint64(getU64(b, 40))
	s.TXErrors = uint64(getU64(b, 48))
	s.CpRXPackets = uint64(getU64(b, 56))
	s.CpRXBytes = uint64(getU64(b, 64))
	s.CpTXPackets = uint64(getU64(b, 72))
	s.CpTXBytes = uint64(getU64(b, 80))
	return nil
}

func (s *IfaceStats) marshal() []byte {
	b := make([]byte, 88)
	putU16(b, 0, uint16(s.IfaceID))
	putU64(b, 8, uint64(s.RXPackets))
	putU64(b, 16, uint64(s.RXBytes))
	putU64(b, 24, uint64(s.RXDrops))
	putU64(b, 32, uint64(s.TXPackets))
	putU64(b, 40, uint64(s.TXBytes))
	putU64(b, 48, uint64(s.TXErrors))
	putU64(b, 56, uint64(s.CpRXPackets))
	putU64(b, 64, uint64(s.CpRXBytes))
	putU64(b, 72, uint64(s.CpTXPackets))
	putU64(b, 80, uint64(s.CpTXBytes))
	return b
}

type IfaceStatsGetResp struct {
	NStats uint16
	Stats  []IfaceStats
}

func (s *IfaceStatsGetResp) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("IfaceStatsGetResp: buffer too short: %d < 8", len(b))
	}
	s.NStats = uint16(getU16(b, 0))
	for off := 8; off+88 <= len(b); off += 88 {
		var elem IfaceStats
		if err := elem.unmarshal(b[off : off+88]); err != nil {
			return err
		}
		s.Stats = append(s.Stats, elem)
	}
	return nil
}

func (s *IfaceStatsGetResp) marshal() []byte {
	b := make([]byte, 8)
	putU16(b, 0, uint16(s.NStats))
	for i := range s.Stats {
		b = append(b, s.Stats[i].marshal()...)
	}
	return b
}

type AffinityRXQSetReq struct {
	IfaceID uint16
	RXQID   uint16
	CPUID   uint16
}

func (s *AffinityRXQSetReq) unmarshal(b []byte) error {
	if len(b) < 6 {
		return fmt.Errorf("AffinityRXQSetReq: buffer too short: %d < 6", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.RXQID = uint16(getU16(b, 2))
	s.CPUID = uint16(getU16(b, 4))
	return nil
}

func (s *AffinityRXQSetReq) marshal() []byte {
	b := make([]byte, 6)
	putU16(b, 0, uint16(s.IfaceID))
	putU16(b, 2, uint16(s.RXQID))
	putU16(b, 4, uint16(s.CPUID))
	return b
}

type StatsGetReq struct {
	Flags   StatsFlags
	CPUID   uint16
	Pattern string
}

func (s *StatsGetReq) unmarshal(b []byte) error {
	if len(b) < 68 {
		return fmt.Errorf("StatsGetReq: buffer too short: %d < 68", len(b))
	}
	s.Flags = StatsFlags(getU8(b, 0))
	s.CPUID = uint16(getU16(b, 2))
	s.Pattern = getString(b, 4, 64)
	return nil
}

func (s *StatsGetReq) marshal() []byte {
	b := make([]byte, 68)
	putU16(b, 0, uint16(s.Flags))
	putU16(b, 2, uint16(s.CPUID))
	putString(b, 4, 64, s.Pattern)
	return b
}

type StatsGetResp struct {
	NStats uint16
	Stats  []Stat
}

func (s *StatsGetResp) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("StatsGetResp: buffer too short: %d < 8", len(b))
	}
	s.NStats = uint16(getU16(b, 0))
	for off := 8; off+96 <= len(b); off += 96 {
		var elem Stat
		if err := elem.unmarshal(b[off : off+96]); err != nil {
			return err
		}
		s.Stats = append(s.Stats, elem)
	}
	return nil
}

func (s *StatsGetResp) marshal() []byte {
	b := make([]byte, 8)
	putU16(b, 0, uint16(s.NStats))
	for i := range s.Stats {
		b = append(b, s.Stats[i].marshal()...)
	}
	return b
}

type GraphDumpReq struct {
	Full    bool
	ByLayer bool
	Compact bool
}

func (s *GraphDumpReq) unmarshal(b []byte) error {
	if len(b) < 3 {
		return fmt.Errorf("GraphDumpReq: buffer too short: %d < 3", len(b))
	}
	s.Full = getBool(b, 0)
	s.ByLayer = getBool(b, 1)
	s.Compact = getBool(b, 2)
	return nil
}

func (s *GraphDumpReq) marshal() []byte {
	b := make([]byte, 3)
	putBool(b, 0, s.Full)
	putBool(b, 1, s.ByLayer)
	putBool(b, 2, s.Compact)
	return b
}

type GraphDumpResp struct {
	Buf string
}

func (s *GraphDumpResp) unmarshal(b []byte) error {
	if len(b) < 1 {
		return fmt.Errorf("GraphDumpResp: buffer too short: %d < 1", len(b))
	}
	s.Buf = getString(b, 0, 1)
	return nil
}

func (s *GraphDumpResp) marshal() []byte {
	b := make([]byte, 1)
	putString(b, 0, 1, s.Buf)
	return b
}

type GraphConf struct {
	RXBurstMax uint16
	VectorMax  uint16
}

func (s *GraphConf) unmarshal(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("GraphConf: buffer too short: %d < 4", len(b))
	}
	s.RXBurstMax = uint16(getU16(b, 0))
	s.VectorMax = uint16(getU16(b, 2))
	return nil
}

func (s *GraphConf) marshal() []byte {
	b := make([]byte, 4)
	putU16(b, 0, uint16(s.RXBurstMax))
	putU16(b, 2, uint16(s.VectorMax))
	return b
}

type PacketTraceDumpReq struct {
	MaxPackets uint16
}

func (s *PacketTraceDumpReq) unmarshal(b []byte) error {
	if len(b) < 2 {
		return fmt.Errorf("PacketTraceDumpReq: buffer too short: %d < 2", len(b))
	}
	s.MaxPackets = uint16(getU16(b, 0))
	return nil
}

func (s *PacketTraceDumpReq) marshal() []byte {
	b := make([]byte, 2)
	putU16(b, 0, uint16(s.MaxPackets))
	return b
}

type PacketTraceDumpResp struct {
	NPackets uint16
	Len      uint32
	Trace    string
}

func (s *PacketTraceDumpResp) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("PacketTraceDumpResp: buffer too short: %d < 8", len(b))
	}
	s.NPackets = uint16(getU16(b, 0))
	s.Len = uint32(getU32(b, 4))
	if len(b) > 8 {
		s.Trace = getString(b, 8, len(b)-8)
	}
	return nil
}

func (s *PacketTraceDumpResp) marshal() []byte {
	b := make([]byte, 8)
	putU16(b, 0, uint16(s.NPackets))
	putU32(b, 4, uint32(s.Len))
	b = append(b, []byte(s.Trace)...)
	b = append(b, 0)
	return b
}

type PacketTraceSetReq struct {
	Enabled bool
	All     bool
	IfaceID uint16
}

func (s *PacketTraceSetReq) unmarshal(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("PacketTraceSetReq: buffer too short: %d < 4", len(b))
	}
	s.Enabled = getBool(b, 0)
	s.All = getBool(b, 1)
	s.IfaceID = uint16(getU16(b, 2))
	return nil
}

func (s *PacketTraceSetReq) marshal() []byte {
	b := make([]byte, 4)
	putBool(b, 0, s.Enabled)
	putBool(b, 1, s.All)
	putU16(b, 2, uint16(s.IfaceID))
	return b
}

type AffinityCPUGetResp struct {
	ControlCpus  CPUSet
	DatapathCpus CPUSet
}

func (s *AffinityCPUGetResp) unmarshal(b []byte) error {
	if len(b) < 256 {
		return fmt.Errorf("AffinityCPUGetResp: buffer too short: %d < 256", len(b))
	}
	s.ControlCpus = getCPUSet(b, 0)
	s.DatapathCpus = getCPUSet(b, 128)
	return nil
}

func (s *AffinityCPUGetResp) marshal() []byte {
	b := make([]byte, 256)
	putCPUSet(b, 0, s.ControlCpus)
	putCPUSet(b, 128, s.DatapathCpus)
	return b
}

type AffinityCPUSetReq struct {
	ControlCpus  CPUSet
	DatapathCpus CPUSet
}

func (s *AffinityCPUSetReq) unmarshal(b []byte) error {
	if len(b) < 256 {
		return fmt.Errorf("AffinityCPUSetReq: buffer too short: %d < 256", len(b))
	}
	s.ControlCpus = getCPUSet(b, 0)
	s.DatapathCpus = getCPUSet(b, 128)
	return nil
}

func (s *AffinityCPUSetReq) marshal() []byte {
	b := make([]byte, 256)
	putCPUSet(b, 0, s.ControlCpus)
	putCPUSet(b, 128, s.DatapathCpus)
	return b
}

// Request type constants.
const (
	grAffinityCPUSet   uint32 = 0xacdc0012
	grAffinityCPUGet   uint32 = 0xacdc0011
	grPacketTraceSet   uint32 = 0xacdc0010
	grPacketTraceDump  uint32 = 0xacdc000f
	grPacketTraceClear uint32 = 0xacdc000e
	grGraphConfSet     uint32 = 0xacdc0009
	grGraphConfGet     uint32 = 0xacdc0008
	grGraphDump        uint32 = 0xacdc000d
	grStatsReset       uint32 = 0xacdc000c
	grStatsGet         uint32 = 0xacdc000b
	grAffinityRXQSet   uint32 = 0xacdc000a
	grAffinityRXQList  uint32 = 0xacdc0007
	grIfaceStatsGet    uint32 = 0xacdc0006
	grIfaceSet         uint32 = 0xacdc0005
	grIfaceMACSet      uint32 = 0xacdc0016
	grIfaceMACList     uint32 = 0xacdc0015
	grIfaceMACDel      uint32 = 0xacdc0014
	grIfaceMACAdd      uint32 = 0xacdc0013
	grIfaceList        uint32 = 0xacdc0004
	grIfaceGet         uint32 = 0xacdc0003
	grIfaceDel         uint32 = 0xacdc0002
	grIfaceAdd         uint32 = 0xacdc0001
)

// Event type constants.
const (
	EventIfaceMACChange    uint32 = 0xacdc1008
	EventIfaceStatusDown   uint32 = 0xacdc1007
	EventIfaceStatusUp     uint32 = 0xacdc1006
	EventIfacePostReconfig uint32 = 0xacdc1005
	EventIfaceRemove       uint32 = 0xacdc1004
	EventIfacePreRemove    uint32 = 0xacdc1003
	EventIfacePostAdd      uint32 = 0xacdc1002
	EventIfaceAdd          uint32 = 0xacdc1001
)

func (c *Client) AffinityCPUSet(req *AffinityCPUSetReq) error {
	return c.sendOnly(grAffinityCPUSet, req.marshal())
}

func (c *Client) AffinityCPUGet() (*AffinityCPUGetResp, error) {
	data, err := c.sendRecv(grAffinityCPUGet, nil)
	if err != nil {
		return nil, err
	}
	resp := new(AffinityCPUGetResp)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func (c *Client) PacketTraceSet(req *PacketTraceSetReq) error {
	return c.sendOnly(grPacketTraceSet, req.marshal())
}

func (c *Client) PacketTraceDump(req *PacketTraceDumpReq) (*PacketTraceDumpResp, error) {
	data, err := c.sendRecv(grPacketTraceDump, req.marshal())
	if err != nil {
		return nil, err
	}
	resp := new(PacketTraceDumpResp)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func (c *Client) PacketTraceClear() error {
	return c.sendOnly(grPacketTraceClear, nil)
}

func (c *Client) GraphConfSet(req *GraphConf) error {
	return c.sendOnly(grGraphConfSet, req.marshal())
}

func (c *Client) GraphConfGet() (*GraphConf, error) {
	data, err := c.sendRecv(grGraphConfGet, nil)
	if err != nil {
		return nil, err
	}
	resp := new(GraphConf)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func (c *Client) GraphDump(req *GraphDumpReq) (*GraphDumpResp, error) {
	data, err := c.sendRecv(grGraphDump, req.marshal())
	if err != nil {
		return nil, err
	}
	resp := new(GraphDumpResp)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func (c *Client) StatsReset() error {
	return c.sendOnly(grStatsReset, nil)
}

func (c *Client) StatsGet(req *StatsGetReq) (*StatsGetResp, error) {
	data, err := c.sendRecv(grStatsGet, req.marshal())
	if err != nil {
		return nil, err
	}
	resp := new(StatsGetResp)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func (c *Client) AffinityRXQSet(req *AffinityRXQSetReq) error {
	return c.sendOnly(grAffinityRXQSet, req.marshal())
}

func (c *Client) AffinityRXQList() iter.Seq2[*PortRXQMap, error] {
	return streamIter[PortRXQMap](c, grAffinityRXQList, nil)
}

func (c *Client) IfaceStatsGet() (*IfaceStatsGetResp, error) {
	data, err := c.sendRecv(grIfaceStatsGet, nil)
	if err != nil {
		return nil, err
	}
	resp := new(IfaceStatsGetResp)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func (c *Client) IfaceSet(req *IfaceSetReq) error {
	return c.sendOnly(grIfaceSet, req.marshal())
}

func (c *Client) IfaceMACSet(req *IfaceMACSetReq) error {
	return c.sendOnly(grIfaceMACSet, req.marshal())
}

func (c *Client) IfaceMACList(req *IfaceMACListReq) iter.Seq2[*IfaceMAC, error] {
	return streamIter[IfaceMAC](c, grIfaceMACList, req.marshal())
}

func (c *Client) IfaceMACDel(req *IfaceMACDelReq) error {
	return c.sendOnly(grIfaceMACDel, req.marshal())
}

func (c *Client) IfaceMACAdd(req *IfaceMACAddReq) error {
	return c.sendOnly(grIfaceMACAdd, req.marshal())
}

func (c *Client) IfaceList(req *IfaceListReq) iter.Seq2[*Iface, error] {
	return streamIter[Iface](c, grIfaceList, req.marshal())
}

func (c *Client) IfaceGet(req *IfaceGetReq) (*IfaceGetResp, error) {
	data, err := c.sendRecv(grIfaceGet, req.marshal())
	if err != nil {
		return nil, err
	}
	resp := new(IfaceGetResp)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func (c *Client) IfaceDel(req *IfaceDelReq) error {
	return c.sendOnly(grIfaceDel, req.marshal())
}

func (c *Client) IfaceAdd(req *IfaceAddReq) (*IfaceAddResp, error) {
	data, err := c.sendRecv(grIfaceAdd, req.marshal())
	if err != nil {
		return nil, err
	}
	resp := new(IfaceAddResp)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func init() {
	registerEventDecoder(EventIfaceMACChange, func(b []byte) (any, error) {
		v := new(Iface)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventIfaceStatusDown, func(b []byte) (any, error) {
		v := new(Iface)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventIfaceStatusUp, func(b []byte) (any, error) {
		v := new(Iface)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventIfacePostReconfig, func(b []byte) (any, error) {
		v := new(Iface)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventIfaceRemove, func(b []byte) (any, error) {
		v := new(Iface)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventIfacePreRemove, func(b []byte) (any, error) {
		v := new(Iface)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventIfacePostAdd, func(b []byte) (any, error) {
		v := new(Iface)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventIfaceAdd, func(b []byte) (any, error) {
		v := new(Iface)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
}
