// Code generated by devtools/gen-go.py; DO NOT EDIT.

package grout

import (
	"fmt"
	"iter"
	"net/netip"
)

type Dnat44Policy struct {
	IfaceID uint16
	Match   netip.Addr
	Replace netip.Addr
}

func (s *Dnat44Policy) unmarshal(b []byte) error {
	if len(b) < 12 {
		return fmt.Errorf("Dnat44Policy: buffer too short: %d < 12", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.Match = getIPv4(b, 4)
	s.Replace = getIPv4(b, 8)
	return nil
}

func (s *Dnat44Policy) marshal() []byte {
	b := make([]byte, 12)
	putU16(b, 0, uint16(s.IfaceID))
	putIPv4(b, 4, s.Match)
	putIPv4(b, 8, s.Replace)
	return b
}

type Dnat44AddReq struct {
	Policy  Dnat44Policy
	ExistOk bool
}

func (s *Dnat44AddReq) unmarshal(b []byte) error {
	if len(b) < 16 {
		return fmt.Errorf("Dnat44AddReq: buffer too short: %d < 16", len(b))
	}
	if err := s.Policy.unmarshal(b[0:12]); err != nil {
		return err
	}
	s.ExistOk = getBool(b, 12)
	return nil
}

func (s *Dnat44AddReq) marshal() []byte {
	b := make([]byte, 16)
	copy(b[0:], s.Policy.marshal())
	putBool(b, 12, s.ExistOk)
	return b
}

type Dnat44DelReq struct {
	IfaceID   uint16
	Match     netip.Addr
	MissingOk bool
}

func (s *Dnat44DelReq) unmarshal(b []byte) error {
	if len(b) < 12 {
		return fmt.Errorf("Dnat44DelReq: buffer too short: %d < 12", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.Match = getIPv4(b, 4)
	s.MissingOk = getBool(b, 8)
	return nil
}

func (s *Dnat44DelReq) marshal() []byte {
	b := make([]byte, 12)
	putU16(b, 0, uint16(s.IfaceID))
	putIPv4(b, 4, s.Match)
	putBool(b, 8, s.MissingOk)
	return b
}

type Dnat44ListReq struct {
	VRFID uint16
}

func (s *Dnat44ListReq) unmarshal(b []byte) error {
	if len(b) < 2 {
		return fmt.Errorf("Dnat44ListReq: buffer too short: %d < 2", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	return nil
}

func (s *Dnat44ListReq) marshal() []byte {
	b := make([]byte, 2)
	putU16(b, 0, uint16(s.VRFID))
	return b
}

type Snat44Policy struct {
	IfaceID uint16
	Net     IPv4Net
	Replace netip.Addr
}

func (s *Snat44Policy) unmarshal(b []byte) error {
	if len(b) < 16 {
		return fmt.Errorf("Snat44Policy: buffer too short: %d < 16", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.Net = getIPv4Net(b, 4, 8)
	s.Replace = getIPv4(b, 12)
	return nil
}

func (s *Snat44Policy) marshal() []byte {
	b := make([]byte, 16)
	putU16(b, 0, uint16(s.IfaceID))
	putIPv4Net(b, 4, 8, s.Net)
	putIPv4(b, 12, s.Replace)
	return b
}

type Snat44AddReq struct {
	Policy  Snat44Policy
	ExistOk bool
}

func (s *Snat44AddReq) unmarshal(b []byte) error {
	if len(b) < 20 {
		return fmt.Errorf("Snat44AddReq: buffer too short: %d < 20", len(b))
	}
	if err := s.Policy.unmarshal(b[0:16]); err != nil {
		return err
	}
	s.ExistOk = getBool(b, 16)
	return nil
}

func (s *Snat44AddReq) marshal() []byte {
	b := make([]byte, 20)
	copy(b[0:], s.Policy.marshal())
	putBool(b, 16, s.ExistOk)
	return b
}

type Snat44DelReq struct {
	Policy    Snat44Policy
	MissingOk bool
}

func (s *Snat44DelReq) unmarshal(b []byte) error {
	if len(b) < 20 {
		return fmt.Errorf("Snat44DelReq: buffer too short: %d < 20", len(b))
	}
	if err := s.Policy.unmarshal(b[0:16]); err != nil {
		return err
	}
	s.MissingOk = getBool(b, 16)
	return nil
}

func (s *Snat44DelReq) marshal() []byte {
	b := make([]byte, 20)
	copy(b[0:], s.Policy.marshal())
	putBool(b, 16, s.MissingOk)
	return b
}

// Request type constants.
const (
	grSnat44List uint32 = 0x0bad0006
	grSnat44Del  uint32 = 0x0bad0005
	grSnat44Add  uint32 = 0x0bad0004
	grDnat44List uint32 = 0x0bad0003
	grDnat44Del  uint32 = 0x0bad0002
	grDnat44Add  uint32 = 0x0bad0001
)

func (c *Client) Snat44List() iter.Seq2[*Snat44Policy, error] {
	return streamIter[Snat44Policy](c, grSnat44List, nil)
}

func (c *Client) Snat44Del(req *Snat44DelReq) error {
	return c.sendOnly(grSnat44Del, req.marshal())
}

func (c *Client) Snat44Add(req *Snat44AddReq) error {
	return c.sendOnly(grSnat44Add, req.marshal())
}

func (c *Client) Dnat44List(req *Dnat44ListReq) iter.Seq2[*Dnat44Policy, error] {
	return streamIter[Dnat44Policy](c, grDnat44List, req.marshal())
}

func (c *Client) Dnat44Del(req *Dnat44DelReq) error {
	return c.sendOnly(grDnat44Del, req.marshal())
}

func (c *Client) Dnat44Add(req *Dnat44AddReq) error {
	return c.sendOnly(grDnat44Add, req.marshal())
}
