// Code generated by devtools/gen-go.py; DO NOT EDIT.

package grout

import (
	"fmt"
	"net/netip"
)

type SRV6EncapBehavior uint8

const (
	SrHEncaps    SRV6EncapBehavior = 0
	SrHEncapsRed SRV6EncapBehavior = 1
)

type SRV6Behavior uint16

const (
	SrBehaviorEnd     SRV6Behavior = 1
	SrBehaviorEndT    SRV6Behavior = 9
	SrBehaviorEndDt6  SRV6Behavior = 18
	SrBehaviorEndDt4  SRV6Behavior = 19
	SrBehaviorEndDt46 SRV6Behavior = 20
)

type SRV6Flags uint8

const (
	SrFlFlavorPsp      SRV6Flags = 1
	SrFlFlavorUsd      SRV6Flags = 2
	SrFlFlavorNextCsid SRV6Flags = 4
)

// Constants from #define macros.
const (
	SRV6RouteSeglistCountMax = 60
)

type SRV6TunsrcSetReq struct {
	Addr netip.Addr
}

func (s *SRV6TunsrcSetReq) unmarshal(b []byte) error {
	if len(b) < 16 {
		return fmt.Errorf("SRV6TunsrcSetReq: buffer too short: %d < 16", len(b))
	}
	s.Addr = getIPv6(b, 0)
	return nil
}

func (s *SRV6TunsrcSetReq) marshal() []byte {
	b := make([]byte, 16)
	putIPv6(b, 0, s.Addr)
	return b
}

type SRV6TunsrcShowResp struct {
	Addr netip.Addr
}

func (s *SRV6TunsrcShowResp) unmarshal(b []byte) error {
	if len(b) < 16 {
		return fmt.Errorf("SRV6TunsrcShowResp: buffer too short: %d < 16", len(b))
	}
	s.Addr = getIPv6(b, 0)
	return nil
}

func (s *SRV6TunsrcShowResp) marshal() []byte {
	b := make([]byte, 16)
	putIPv6(b, 0, s.Addr)
	return b
}

// Request type constants.
const (
	grSRV6TunsrcShow  uint32 = 0xfeef0003
	grSRV6TunsrcClear uint32 = 0xfeef0002
	grSRV6TunsrcSet   uint32 = 0xfeef0001
)

func (c *Client) SRV6TunsrcShow() (*SRV6TunsrcShowResp, error) {
	data, err := c.sendRecv(grSRV6TunsrcShow, nil)
	if err != nil {
		return nil, err
	}
	resp := new(SRV6TunsrcShowResp)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func (c *Client) SRV6TunsrcClear() error {
	return c.sendOnly(grSRV6TunsrcClear, nil)
}

func (c *Client) SRV6TunsrcSet(req *SRV6TunsrcSetReq) error {
	return c.sendOnly(grSRV6TunsrcSet, req.marshal())
}
