// Code generated by devtools/gen-go.py; DO NOT EDIT.

package grout

import (
	"fmt"
	"net/netip"
)

type IfaceInfoIPIP struct {
	Local  netip.Addr
	Remote netip.Addr
}

func (s *IfaceInfoIPIP) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("IfaceInfoIPIP: buffer too short: %d < 8", len(b))
	}
	s.Local = getIPv4(b, 0)
	s.Remote = getIPv4(b, 4)
	return nil
}

func (s *IfaceInfoIPIP) marshal() []byte {
	b := make([]byte, 8)
	putIPv4(b, 0, s.Local)
	putIPv4(b, 4, s.Remote)
	return b
}
