// Code generated by devtools/gen-go.py; DO NOT EDIT.

package grout

import (
	"fmt"
	"iter"
)

// Constants from #define macros.
const (
	ApiMaxMsgLen    = 0x20000
	ApiVersion      = 3
	EventAll        = 0xffffffff
	LogLevelMax     = 8
	LogLevelMin     = 1
	DefaultSockPath = "/run/grout.sock"
)

const (
	eventHeaderSize = 16
	reqHeaderSize   = 12
	respHeaderSize  = 12
)

type ApiRequest struct {
	ID         uint32
	Type       uint32
	PayloadLen uint32
}

func (s *ApiRequest) unmarshal(b []byte) error {
	if len(b) < 12 {
		return fmt.Errorf("ApiRequest: buffer too short: %d < 12", len(b))
	}
	s.ID = uint32(getU32(b, 0))
	s.Type = uint32(getU32(b, 4))
	s.PayloadLen = uint32(getU32(b, 8))
	return nil
}

func (s *ApiRequest) marshal() []byte {
	b := make([]byte, 12)
	putU32(b, 0, uint32(s.ID))
	putU32(b, 4, uint32(s.Type))
	putU32(b, 8, uint32(s.PayloadLen))
	return b
}

type ApiResponse struct {
	ForID      uint32
	Status     uint32
	PayloadLen uint32
}

func (s *ApiResponse) unmarshal(b []byte) error {
	if len(b) < 12 {
		return fmt.Errorf("ApiResponse: buffer too short: %d < 12", len(b))
	}
	s.ForID = uint32(getU32(b, 0))
	s.Status = uint32(getU32(b, 4))
	s.PayloadLen = uint32(getU32(b, 8))
	return nil
}

func (s *ApiResponse) marshal() []byte {
	b := make([]byte, 12)
	putU32(b, 0, uint32(s.ForID))
	putU32(b, 4, uint32(s.Status))
	putU32(b, 8, uint32(s.PayloadLen))
	return b
}

type Empty struct{}

func (s *Empty) unmarshal(b []byte) error {
	if len(b) < 0 {
		return fmt.Errorf("Empty: buffer too short: %d < 0", len(b))
	}
	return nil
}

func (s *Empty) marshal() []byte {
	b := make([]byte, 0)
	return b
}

type HelloReq struct {
	ApiVersion uint32
	Version    string
}

func (s *HelloReq) unmarshal(b []byte) error {
	if len(b) < 132 {
		return fmt.Errorf("HelloReq: buffer too short: %d < 132", len(b))
	}
	s.ApiVersion = uint32(getU32(b, 0))
	s.Version = getString(b, 4, 128)
	return nil
}

func (s *HelloReq) marshal() []byte {
	b := make([]byte, 132)
	putU32(b, 0, uint32(s.ApiVersion))
	putString(b, 4, 128, s.Version)
	return b
}

type LogPacketsSetReq struct {
	Enabled bool
}

func (s *LogPacketsSetReq) unmarshal(b []byte) error {
	if len(b) < 1 {
		return fmt.Errorf("LogPacketsSetReq: buffer too short: %d < 1", len(b))
	}
	s.Enabled = getBool(b, 0)
	return nil
}

func (s *LogPacketsSetReq) marshal() []byte {
	b := make([]byte, 1)
	putBool(b, 0, s.Enabled)
	return b
}

type LogLevelListReq struct {
	ShowAll bool
}

func (s *LogLevelListReq) unmarshal(b []byte) error {
	if len(b) < 1 {
		return fmt.Errorf("LogLevelListReq: buffer too short: %d < 1", len(b))
	}
	s.ShowAll = getBool(b, 0)
	return nil
}

func (s *LogLevelListReq) marshal() []byte {
	b := make([]byte, 1)
	putBool(b, 0, s.ShowAll)
	return b
}

type LogEntry struct {
	Name  string
	Level uint32
}

func (s *LogEntry) unmarshal(b []byte) error {
	if len(b) < 68 {
		return fmt.Errorf("LogEntry: buffer too short: %d < 68", len(b))
	}
	s.Name = getString(b, 0, 64)
	s.Level = uint32(getU32(b, 64))
	return nil
}

func (s *LogEntry) marshal() []byte {
	b := make([]byte, 68)
	putString(b, 0, 64, s.Name)
	putU32(b, 64, uint32(s.Level))
	return b
}

type LogLevelSetReq struct {
	Pattern string
	Level   uint32
}

func (s *LogLevelSetReq) unmarshal(b []byte) error {
	if len(b) < 68 {
		return fmt.Errorf("LogLevelSetReq: buffer too short: %d < 68", len(b))
	}
	s.Pattern = getString(b, 0, 64)
	s.Level = uint32(getU32(b, 64))
	return nil
}

func (s *LogLevelSetReq) marshal() []byte {
	b := make([]byte, 68)
	putString(b, 0, 64, s.Pattern)
	putU32(b, 64, uint32(s.Level))
	return b
}

type EventSubscribeReq struct {
	SuppressSelfEvents bool
	EvType             uint32
}

func (s *EventSubscribeReq) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("EventSubscribeReq: buffer too short: %d < 8", len(b))
	}
	s.SuppressSelfEvents = getBool(b, 0)
	s.EvType = uint32(getU32(b, 4))
	return nil
}

func (s *EventSubscribeReq) marshal() []byte {
	b := make([]byte, 8)
	putBool(b, 0, s.SuppressSelfEvents)
	putU32(b, 4, uint32(s.EvType))
	return b
}

type ApiEvent struct {
	EvType     uint32
	PayloadLen uint64
}

func (s *ApiEvent) unmarshal(b []byte) error {
	if len(b) < 16 {
		return fmt.Errorf("ApiEvent: buffer too short: %d < 16", len(b))
	}
	s.EvType = uint32(getU32(b, 0))
	s.PayloadLen = uint64(getU64(b, 8))
	return nil
}

func (s *ApiEvent) marshal() []byte {
	b := make([]byte, 16)
	putU32(b, 0, uint32(s.EvType))
	putU64(b, 8, uint64(s.PayloadLen))
	return b
}

// Request type constants.
const (
	grEventUnsubscribe uint32 = 0xcafe1986
	grEventSubscribe   uint32 = 0xcafe1985
	grLogLevelSet      uint32 = 0xcafe1984
	grLogLevelList     uint32 = 0xcafe1983
	grLogPacketsSet    uint32 = 0xcafe1982
	grHello            uint32 = 0xcafe1981
)

func (c *Client) EventUnsubscribe() error {
	return c.sendOnly(grEventUnsubscribe, nil)
}

func (c *Client) EventSubscribe(req *EventSubscribeReq) error {
	return c.sendOnly(grEventSubscribe, req.marshal())
}

func (c *Client) LogLevelSet(req *LogLevelSetReq) error {
	return c.sendOnly(grLogLevelSet, req.marshal())
}

func (c *Client) LogLevelList(req *LogLevelListReq) iter.Seq2[*LogEntry, error] {
	return streamIter[LogEntry](c, grLogLevelList, req.marshal())
}

func (c *Client) LogPacketsSet(req *LogPacketsSetReq) error {
	return c.sendOnly(grLogPacketsSet, req.marshal())
}

func (c *Client) Hello(req *HelloReq) error {
	return c.sendOnly(grHello, req.marshal())
}
