// Code generated by devtools/gen-go.py; DO NOT EDIT.

package grout

import (
	"fmt"
	"iter"
	"net/netip"
)

type DHCPState uint8

const (
	Init       DHCPState = 0
	Selecting  DHCPState = 1
	Requesting DHCPState = 2
	Bound      DHCPState = 3
	Renewing   DHCPState = 4
	Rebinding  DHCPState = 5
)

type DHCPStatus struct {
	IfaceID     uint16
	State       DHCPState
	ServerIP    netip.Addr
	AssignedIP  netip.Addr
	LeaseTime   uint32
	RenewalTime uint32
	RebindTime  uint32
}

func (s *DHCPStatus) unmarshal(b []byte) error {
	if len(b) < 24 {
		return fmt.Errorf("DHCPStatus: buffer too short: %d < 24", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.State = DHCPState(getU8(b, 2))
	s.ServerIP = getIPv4(b, 4)
	s.AssignedIP = getIPv4(b, 8)
	s.LeaseTime = uint32(getU32(b, 12))
	s.RenewalTime = uint32(getU32(b, 16))
	s.RebindTime = uint32(getU32(b, 20))
	return nil
}

func (s *DHCPStatus) marshal() []byte {
	b := make([]byte, 24)
	putU16(b, 0, uint16(s.IfaceID))
	putU8(b, 2, uint8(s.State))
	putIPv4(b, 4, s.ServerIP)
	putIPv4(b, 8, s.AssignedIP)
	putU32(b, 12, uint32(s.LeaseTime))
	putU32(b, 16, uint32(s.RenewalTime))
	putU32(b, 20, uint32(s.RebindTime))
	return b
}

type DHCPStartReq struct {
	IfaceID uint16
}

func (s *DHCPStartReq) unmarshal(b []byte) error {
	if len(b) < 2 {
		return fmt.Errorf("DHCPStartReq: buffer too short: %d < 2", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	return nil
}

func (s *DHCPStartReq) marshal() []byte {
	b := make([]byte, 2)
	putU16(b, 0, uint16(s.IfaceID))
	return b
}

type DHCPStopReq struct {
	IfaceID uint16
}

func (s *DHCPStopReq) unmarshal(b []byte) error {
	if len(b) < 2 {
		return fmt.Errorf("DHCPStopReq: buffer too short: %d < 2", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	return nil
}

func (s *DHCPStopReq) marshal() []byte {
	b := make([]byte, 2)
	putU16(b, 0, uint16(s.IfaceID))
	return b
}

// Request type constants.
const (
	grDHCPStop  uint32 = 0xd4c90003
	grDHCPStart uint32 = 0xd4c90002
	grDHCPList  uint32 = 0xd4c90001
)

func (c *Client) DHCPStop(req *DHCPStopReq) error {
	return c.sendOnly(grDHCPStop, req.marshal())
}

func (c *Client) DHCPStart(req *DHCPStartReq) error {
	return c.sendOnly(grDHCPStart, req.marshal())
}

func (c *Client) DHCPList() iter.Seq2[*DHCPStatus, error] {
	return streamIter[DHCPStatus](c, grDHCPList, nil)
}
