// Code generated by devtools/gen-go.py; DO NOT EDIT.

package grout

import (
	"fmt"
	"iter"
	"net/netip"
)

type IP4Ifaddr struct {
	IfaceID uint16
	Addr    IPv4Net
}

func (s *IP4Ifaddr) unmarshal(b []byte) error {
	if len(b) < 12 {
		return fmt.Errorf("IP4Ifaddr: buffer too short: %d < 12", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.Addr = getIPv4Net(b, 4, 8)
	return nil
}

func (s *IP4Ifaddr) marshal() []byte {
	b := make([]byte, 12)
	putU16(b, 0, uint16(s.IfaceID))
	putIPv4Net(b, 4, 8, s.Addr)
	return b
}

type IP4Route struct {
	Dest   IPv4Net
	VRFID  uint16
	Origin NHOrigin
	NH     Nexthop
}

func (s *IP4Route) unmarshal(b []byte) error {
	if len(b) < 24 {
		return fmt.Errorf("IP4Route: buffer too short: %d < 24", len(b))
	}
	s.Dest = getIPv4Net(b, 0, 4)
	s.VRFID = uint16(getU16(b, 8))
	s.Origin = NHOrigin(getU8(b, 10))
	if err := s.NH.unmarshal(b[12:]); err != nil {
		return err
	}
	return nil
}

func (s *IP4Route) marshal() []byte {
	b := make([]byte, 24)
	putIPv4Net(b, 0, 4, s.Dest)
	putU16(b, 8, uint16(s.VRFID))
	putU8(b, 10, uint8(s.Origin))
	{
		d := s.NH.marshal()
		copy(b[12:], d[:min(len(d), len(b)-12)])
		if len(d) > 12 {
			b = append(b, d[12:]...)
		}
	}
	return b
}

type IP4RouteAddReq struct {
	VRFID   uint16
	Dest    IPv4Net
	NH      netip.Addr
	NHID    uint32
	Origin  NHOrigin
	ExistOk uint8
}

func (s *IP4RouteAddReq) unmarshal(b []byte) error {
	if len(b) < 24 {
		return fmt.Errorf("IP4RouteAddReq: buffer too short: %d < 24", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	s.Dest = getIPv4Net(b, 4, 8)
	s.NH = getIPv4(b, 12)
	s.NHID = uint32(getU32(b, 16))
	s.Origin = NHOrigin(getU8(b, 20))
	s.ExistOk = uint8(getU8(b, 21))
	return nil
}

func (s *IP4RouteAddReq) marshal() []byte {
	b := make([]byte, 24)
	putU16(b, 0, uint16(s.VRFID))
	putIPv4Net(b, 4, 8, s.Dest)
	putIPv4(b, 12, s.NH)
	putU32(b, 16, uint32(s.NHID))
	putU8(b, 20, uint8(s.Origin))
	putU8(b, 21, uint8(s.ExistOk))
	return b
}

type IP4RouteDelReq struct {
	VRFID     uint16
	Dest      IPv4Net
	MissingOk uint8
}

func (s *IP4RouteDelReq) unmarshal(b []byte) error {
	if len(b) < 16 {
		return fmt.Errorf("IP4RouteDelReq: buffer too short: %d < 16", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	s.Dest = getIPv4Net(b, 4, 8)
	s.MissingOk = uint8(getU8(b, 12))
	return nil
}

func (s *IP4RouteDelReq) marshal() []byte {
	b := make([]byte, 16)
	putU16(b, 0, uint16(s.VRFID))
	putIPv4Net(b, 4, 8, s.Dest)
	putU8(b, 12, uint8(s.MissingOk))
	return b
}

type IP4RouteGetReq struct {
	VRFID uint16
	Dest  netip.Addr
}

func (s *IP4RouteGetReq) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("IP4RouteGetReq: buffer too short: %d < 8", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	s.Dest = getIPv4(b, 4)
	return nil
}

func (s *IP4RouteGetReq) marshal() []byte {
	b := make([]byte, 8)
	putU16(b, 0, uint16(s.VRFID))
	putIPv4(b, 4, s.Dest)
	return b
}

type IP4RouteGetResp struct {
	NH Nexthop
}

func (s *IP4RouteGetResp) unmarshal(b []byte) error {
	if len(b) < 12 {
		return fmt.Errorf("IP4RouteGetResp: buffer too short: %d < 12", len(b))
	}
	if err := s.NH.unmarshal(b[0:]); err != nil {
		return err
	}
	return nil
}

func (s *IP4RouteGetResp) marshal() []byte {
	b := make([]byte, 12)
	{
		d := s.NH.marshal()
		copy(b[0:], d[:min(len(d), len(b)-0)])
		if len(d) > 12 {
			b = append(b, d[12:]...)
		}
	}
	return b
}

type IP4RouteListReq struct {
	VRFID    uint16
	MaxCount uint16
}

func (s *IP4RouteListReq) unmarshal(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("IP4RouteListReq: buffer too short: %d < 4", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	s.MaxCount = uint16(getU16(b, 2))
	return nil
}

func (s *IP4RouteListReq) marshal() []byte {
	b := make([]byte, 4)
	putU16(b, 0, uint16(s.VRFID))
	putU16(b, 2, uint16(s.MaxCount))
	return b
}

type IP4AddrAddReq struct {
	Addr    IP4Ifaddr
	ExistOk uint8
}

func (s *IP4AddrAddReq) unmarshal(b []byte) error {
	if len(b) < 16 {
		return fmt.Errorf("IP4AddrAddReq: buffer too short: %d < 16", len(b))
	}
	if err := s.Addr.unmarshal(b[0:12]); err != nil {
		return err
	}
	s.ExistOk = uint8(getU8(b, 12))
	return nil
}

func (s *IP4AddrAddReq) marshal() []byte {
	b := make([]byte, 16)
	copy(b[0:], s.Addr.marshal())
	putU8(b, 12, uint8(s.ExistOk))
	return b
}

type IP4AddrDelReq struct {
	Addr      IP4Ifaddr
	MissingOk uint8
}

func (s *IP4AddrDelReq) unmarshal(b []byte) error {
	if len(b) < 16 {
		return fmt.Errorf("IP4AddrDelReq: buffer too short: %d < 16", len(b))
	}
	if err := s.Addr.unmarshal(b[0:12]); err != nil {
		return err
	}
	s.MissingOk = uint8(getU8(b, 12))
	return nil
}

func (s *IP4AddrDelReq) marshal() []byte {
	b := make([]byte, 16)
	copy(b[0:], s.Addr.marshal())
	putU8(b, 12, uint8(s.MissingOk))
	return b
}

type IP4AddrListReq struct {
	VRFID   uint16
	IfaceID uint16
}

func (s *IP4AddrListReq) unmarshal(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("IP4AddrListReq: buffer too short: %d < 4", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	s.IfaceID = uint16(getU16(b, 2))
	return nil
}

func (s *IP4AddrListReq) marshal() []byte {
	b := make([]byte, 4)
	putU16(b, 0, uint16(s.VRFID))
	putU16(b, 2, uint16(s.IfaceID))
	return b
}

type IP4AddrFlushReq struct {
	IfaceID uint16
}

func (s *IP4AddrFlushReq) unmarshal(b []byte) error {
	if len(b) < 2 {
		return fmt.Errorf("IP4AddrFlushReq: buffer too short: %d < 2", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	return nil
}

func (s *IP4AddrFlushReq) marshal() []byte {
	b := make([]byte, 2)
	putU16(b, 0, uint16(s.IfaceID))
	return b
}

type IP4ICMPSendReq struct {
	Addr   netip.Addr
	VRF    uint16
	Ident  uint16
	SeqNum uint16
	Ttl    uint8
}

func (s *IP4ICMPSendReq) unmarshal(b []byte) error {
	if len(b) < 12 {
		return fmt.Errorf("IP4ICMPSendReq: buffer too short: %d < 12", len(b))
	}
	s.Addr = getIPv4(b, 0)
	s.VRF = uint16(getU16(b, 4))
	s.Ident = uint16(getU16(b, 6))
	s.SeqNum = uint16(getU16(b, 8))
	s.Ttl = uint8(getU8(b, 10))
	return nil
}

func (s *IP4ICMPSendReq) marshal() []byte {
	b := make([]byte, 12)
	putIPv4(b, 0, s.Addr)
	putU16(b, 4, uint16(s.VRF))
	putU16(b, 6, uint16(s.Ident))
	putU16(b, 8, uint16(s.SeqNum))
	putU8(b, 10, uint8(s.Ttl))
	return b
}

type IP4ICMPRecvReq struct {
	Ident  uint16
	SeqNum uint16
}

func (s *IP4ICMPRecvReq) unmarshal(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("IP4ICMPRecvReq: buffer too short: %d < 4", len(b))
	}
	s.Ident = uint16(getU16(b, 0))
	s.SeqNum = uint16(getU16(b, 2))
	return nil
}

func (s *IP4ICMPRecvReq) marshal() []byte {
	b := make([]byte, 4)
	putU16(b, 0, uint16(s.Ident))
	putU16(b, 2, uint16(s.SeqNum))
	return b
}

type IP4ICMPRecvResp struct {
	Type         uint8
	Code         uint8
	Ttl          uint8
	Ident        uint16
	SeqNum       uint16
	SrcAddr      netip.Addr
	ResponseTime int64
}

func (s *IP4ICMPRecvResp) unmarshal(b []byte) error {
	if len(b) < 24 {
		return fmt.Errorf("IP4ICMPRecvResp: buffer too short: %d < 24", len(b))
	}
	s.Type = uint8(getU8(b, 0))
	s.Code = uint8(getU8(b, 1))
	s.Ttl = uint8(getU8(b, 2))
	s.Ident = uint16(getU16(b, 4))
	s.SeqNum = uint16(getU16(b, 6))
	s.SrcAddr = getIPv4(b, 8)
	s.ResponseTime = int64(getU64(b, 16))
	return nil
}

func (s *IP4ICMPRecvResp) marshal() []byte {
	b := make([]byte, 24)
	putU8(b, 0, uint8(s.Type))
	putU8(b, 1, uint8(s.Code))
	putU8(b, 2, uint8(s.Ttl))
	putU16(b, 4, uint16(s.Ident))
	putU16(b, 6, uint16(s.SeqNum))
	putIPv4(b, 8, s.SrcAddr)
	putU64(b, 16, uint64(s.ResponseTime))
	return b
}

type Fib4Info struct {
	VRFID      uint16
	MaxRoutes  uint32
	UsedRoutes uint32
	NumTbl8    uint32
	UsedTbl8   uint32
}

func (s *Fib4Info) unmarshal(b []byte) error {
	if len(b) < 20 {
		return fmt.Errorf("Fib4Info: buffer too short: %d < 20", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	s.MaxRoutes = uint32(getU32(b, 4))
	s.UsedRoutes = uint32(getU32(b, 8))
	s.NumTbl8 = uint32(getU32(b, 12))
	s.UsedTbl8 = uint32(getU32(b, 16))
	return nil
}

func (s *Fib4Info) marshal() []byte {
	b := make([]byte, 20)
	putU16(b, 0, uint16(s.VRFID))
	putU32(b, 4, uint32(s.MaxRoutes))
	putU32(b, 8, uint32(s.UsedRoutes))
	putU32(b, 12, uint32(s.NumTbl8))
	putU32(b, 16, uint32(s.UsedTbl8))
	return b
}

type IP4FIBDefaultSetReq struct {
	MaxRoutes uint32
}

func (s *IP4FIBDefaultSetReq) unmarshal(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("IP4FIBDefaultSetReq: buffer too short: %d < 4", len(b))
	}
	s.MaxRoutes = uint32(getU32(b, 0))
	return nil
}

func (s *IP4FIBDefaultSetReq) marshal() []byte {
	b := make([]byte, 4)
	putU32(b, 0, uint32(s.MaxRoutes))
	return b
}

type IP4FIBInfoListReq struct {
	VRFID uint16
}

func (s *IP4FIBInfoListReq) unmarshal(b []byte) error {
	if len(b) < 2 {
		return fmt.Errorf("IP4FIBInfoListReq: buffer too short: %d < 2", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	return nil
}

func (s *IP4FIBInfoListReq) marshal() []byte {
	b := make([]byte, 2)
	putU16(b, 0, uint16(s.VRFID))
	return b
}

// Request type constants.
const (
	grIP4FIBInfoList   uint32 = 0xf00d000c
	grIP4FIBDefaultSet uint32 = 0xf00d000b
	grIP4ICMPRecv      uint32 = 0xf00d000a
	grIP4ICMPSend      uint32 = 0xf00d0009
	grIP4AddrFlush     uint32 = 0xf00d0008
	grIP4AddrList      uint32 = 0xf00d0007
	grIP4AddrDel       uint32 = 0xf00d0006
	grIP4AddrAdd       uint32 = 0xf00d0005
	grIP4RouteList     uint32 = 0xf00d0004
	grIP4RouteGet      uint32 = 0xf00d0003
	grIP4RouteDel      uint32 = 0xf00d0002
	grIP4RouteAdd      uint32 = 0xf00d0001
)

// Event type constants.
const (
	EventIPRouteDel uint32 = 0xf00d1004
	EventIPRouteAdd uint32 = 0xf00d1003
	EventIPAddrDel  uint32 = 0xf00d1002
	EventIPAddrAdd  uint32 = 0xf00d1001
)

func (c *Client) IP4FIBInfoList(req *IP4FIBInfoListReq) iter.Seq2[*Fib4Info, error] {
	return streamIter[Fib4Info](c, grIP4FIBInfoList, req.marshal())
}

func (c *Client) IP4FIBDefaultSet(req *IP4FIBDefaultSetReq) error {
	return c.sendOnly(grIP4FIBDefaultSet, req.marshal())
}

func (c *Client) IP4ICMPRecv(req *IP4ICMPRecvReq) (*IP4ICMPRecvResp, error) {
	data, err := c.sendRecv(grIP4ICMPRecv, req.marshal())
	if err != nil {
		return nil, err
	}
	resp := new(IP4ICMPRecvResp)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func (c *Client) IP4ICMPSend(req *IP4ICMPSendReq) error {
	return c.sendOnly(grIP4ICMPSend, req.marshal())
}

func (c *Client) IP4AddrFlush(req *IP4AddrFlushReq) error {
	return c.sendOnly(grIP4AddrFlush, req.marshal())
}

func (c *Client) IP4AddrList(req *IP4AddrListReq) iter.Seq2[*IP4Ifaddr, error] {
	return streamIter[IP4Ifaddr](c, grIP4AddrList, req.marshal())
}

func (c *Client) IP4AddrDel(req *IP4AddrDelReq) error {
	return c.sendOnly(grIP4AddrDel, req.marshal())
}

func (c *Client) IP4AddrAdd(req *IP4AddrAddReq) error {
	return c.sendOnly(grIP4AddrAdd, req.marshal())
}

func (c *Client) IP4RouteList(req *IP4RouteListReq) iter.Seq2[*IP4Route, error] {
	return streamIter[IP4Route](c, grIP4RouteList, req.marshal())
}

func (c *Client) IP4RouteGet(req *IP4RouteGetReq) (*IP4RouteGetResp, error) {
	data, err := c.sendRecv(grIP4RouteGet, req.marshal())
	if err != nil {
		return nil, err
	}
	resp := new(IP4RouteGetResp)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func (c *Client) IP4RouteDel(req *IP4RouteDelReq) error {
	return c.sendOnly(grIP4RouteDel, req.marshal())
}

func (c *Client) IP4RouteAdd(req *IP4RouteAddReq) error {
	return c.sendOnly(grIP4RouteAdd, req.marshal())
}

func init() {
	registerEventDecoder(EventIPRouteDel, func(b []byte) (any, error) {
		v := new(IP4Route)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventIPRouteAdd, func(b []byte) (any, error) {
		v := new(IP4Route)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventIPAddrDel, func(b []byte) (any, error) {
		v := new(IP4Ifaddr)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventIPAddrAdd, func(b []byte) (any, error) {
		v := new(IP4Ifaddr)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
}
