// Code generated by devtools/gen-go.py; DO NOT EDIT.

package grout

import (
	"fmt"
	"iter"
	"net/netip"
)

type BridgeFlags uint16

const (
	BridgeFNoFlood BridgeFlags = 1
	BridgeFNoLearn BridgeFlags = 2
)

type FDBFlags uint8

const (
	FDBFStatic FDBFlags = 1
	FDBFLearn  FDBFlags = 2
	FDBFExtern FDBFlags = 4
)

type FloodType uint8

const (
	FloodTVtep FloodType = 1
)

// Constants from #define macros.
const (
	BridgeDefaultAgeing        = 300
	BridgeMaxMembers           = 64
	BridgeSetAgeingTime        = 0x100000000
	BridgeSetFlags      uint64 = 0x200000000
	BridgeSetMAC        uint64 = 0x400000000
	VXLANSetDstPort     uint64 = 0x400000000
	VXLANSetEncapVRF    uint64 = 0x200000000
	VXLANSetLocal       uint64 = 0x800000000
	VXLANSetMAC         uint64 = 0x2000000000
	VXLANSetVNI                = 0x100000000
)

type IfaceInfoBridge struct {
	AgeingTime uint16
	Flags      BridgeFlags
	MAC        EtherAddr
	NMembers   uint16
	Members    [64]uint16
}

func (s *IfaceInfoBridge) unmarshal(b []byte) error {
	if len(b) < 140 {
		return fmt.Errorf("IfaceInfoBridge: buffer too short: %d < 140", len(b))
	}
	s.AgeingTime = uint16(getU16(b, 0))
	s.Flags = BridgeFlags(getU8(b, 2))
	s.MAC = getEther(b, 4)
	s.NMembers = uint16(getU16(b, 10))
	return nil
}

func (s *IfaceInfoBridge) marshal() []byte {
	b := make([]byte, 140)
	putU16(b, 0, uint16(s.AgeingTime))
	putU16(b, 2, uint16(s.Flags))
	putEther(b, 4, s.MAC)
	putU16(b, 10, uint16(s.NMembers))
	return b
}

type IfaceInfoVXLAN struct {
	VNI        uint32
	EncapVRFID uint16
	DstPort    uint16
	Local      netip.Addr
	MAC        EtherAddr
}

func (s *IfaceInfoVXLAN) unmarshal(b []byte) error {
	if len(b) < 36 {
		return fmt.Errorf("IfaceInfoVXLAN: buffer too short: %d < 36", len(b))
	}
	s.VNI = uint32(getU32(b, 0))
	s.EncapVRFID = uint16(getU16(b, 4))
	s.DstPort = uint16(getU16(b, 6))
	s.Local = getL3Addr(b, 8)
	s.MAC = getEther(b, 28)
	return nil
}

func (s *IfaceInfoVXLAN) marshal() []byte {
	b := make([]byte, 36)
	putU32(b, 0, uint32(s.VNI))
	putU16(b, 4, uint16(s.EncapVRFID))
	putU16(b, 6, uint16(s.DstPort))
	putL3Addr(b, 8, s.Local)
	putEther(b, 28, s.MAC)
	return b
}

type FDBEntry struct {
	BridgeID uint16
	MAC      EtherAddr
	VLANID   uint16
	IfaceID  uint16
	Vtep     netip.Addr
	Flags    FDBFlags
	LastSeen int64
}

func (s *FDBEntry) unmarshal(b []byte) error {
	if len(b) < 48 {
		return fmt.Errorf("FDBEntry: buffer too short: %d < 48", len(b))
	}
	s.BridgeID = uint16(getU16(b, 0))
	s.MAC = getEther(b, 2)
	s.VLANID = uint16(getU16(b, 8))
	s.IfaceID = uint16(getU16(b, 10))
	s.Vtep = getL3Addr(b, 12)
	s.Flags = FDBFlags(getU8(b, 32))
	s.LastSeen = int64(getU64(b, 40))
	return nil
}

func (s *FDBEntry) marshal() []byte {
	b := make([]byte, 48)
	putU16(b, 0, uint16(s.BridgeID))
	putEther(b, 2, s.MAC)
	putU16(b, 8, uint16(s.VLANID))
	putU16(b, 10, uint16(s.IfaceID))
	putL3Addr(b, 12, s.Vtep)
	putU8(b, 32, uint8(s.Flags))
	putU64(b, 40, uint64(s.LastSeen))
	return b
}

type FDBAddReq struct {
	FDB     FDBEntry
	ExistOk bool
}

func (s *FDBAddReq) unmarshal(b []byte) error {
	if len(b) < 56 {
		return fmt.Errorf("FDBAddReq: buffer too short: %d < 56", len(b))
	}
	if err := s.FDB.unmarshal(b[0:48]); err != nil {
		return err
	}
	s.ExistOk = getBool(b, 48)
	return nil
}

func (s *FDBAddReq) marshal() []byte {
	b := make([]byte, 56)
	copy(b[0:], s.FDB.marshal())
	putBool(b, 48, s.ExistOk)
	return b
}

type FDBDelReq struct {
	BridgeID  uint16
	MAC       EtherAddr
	VLANID    uint16
	MissingOk bool
}

func (s *FDBDelReq) unmarshal(b []byte) error {
	if len(b) < 12 {
		return fmt.Errorf("FDBDelReq: buffer too short: %d < 12", len(b))
	}
	s.BridgeID = uint16(getU16(b, 0))
	s.MAC = getEther(b, 2)
	s.VLANID = uint16(getU16(b, 8))
	s.MissingOk = getBool(b, 10)
	return nil
}

func (s *FDBDelReq) marshal() []byte {
	b := make([]byte, 12)
	putU16(b, 0, uint16(s.BridgeID))
	putEther(b, 2, s.MAC)
	putU16(b, 8, uint16(s.VLANID))
	putBool(b, 10, s.MissingOk)
	return b
}

type FDBFlushReq struct {
	BridgeID uint16
	MAC      EtherAddr
	IfaceID  uint16
	Flags    FDBFlags
}

func (s *FDBFlushReq) unmarshal(b []byte) error {
	if len(b) < 12 {
		return fmt.Errorf("FDBFlushReq: buffer too short: %d < 12", len(b))
	}
	s.BridgeID = uint16(getU16(b, 0))
	s.MAC = getEther(b, 2)
	s.IfaceID = uint16(getU16(b, 8))
	s.Flags = FDBFlags(getU8(b, 10))
	return nil
}

func (s *FDBFlushReq) marshal() []byte {
	b := make([]byte, 12)
	putU16(b, 0, uint16(s.BridgeID))
	putEther(b, 2, s.MAC)
	putU16(b, 8, uint16(s.IfaceID))
	putU8(b, 10, uint8(s.Flags))
	return b
}

type FDBListReq struct {
	BridgeID uint16
	IfaceID  uint16
	Flags    FDBFlags
}

func (s *FDBListReq) unmarshal(b []byte) error {
	if len(b) < 6 {
		return fmt.Errorf("FDBListReq: buffer too short: %d < 6", len(b))
	}
	s.BridgeID = uint16(getU16(b, 0))
	s.IfaceID = uint16(getU16(b, 2))
	s.Flags = FDBFlags(getU8(b, 4))
	return nil
}

func (s *FDBListReq) marshal() []byte {
	b := make([]byte, 6)
	putU16(b, 0, uint16(s.BridgeID))
	putU16(b, 2, uint16(s.IfaceID))
	putU8(b, 4, uint8(s.Flags))
	return b
}

type FDBConfigGetResp struct {
	MaxEntries  uint32
	UsedEntries uint32
}

func (s *FDBConfigGetResp) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("FDBConfigGetResp: buffer too short: %d < 8", len(b))
	}
	s.MaxEntries = uint32(getU32(b, 0))
	s.UsedEntries = uint32(getU32(b, 4))
	return nil
}

func (s *FDBConfigGetResp) marshal() []byte {
	b := make([]byte, 8)
	putU32(b, 0, uint32(s.MaxEntries))
	putU32(b, 4, uint32(s.UsedEntries))
	return b
}

type FDBConfigSetReq struct {
	MaxEntries uint32
}

func (s *FDBConfigSetReq) unmarshal(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("FDBConfigSetReq: buffer too short: %d < 4", len(b))
	}
	s.MaxEntries = uint32(getU32(b, 0))
	return nil
}

func (s *FDBConfigSetReq) marshal() []byte {
	b := make([]byte, 4)
	putU32(b, 0, uint32(s.MaxEntries))
	return b
}

type FloodVtep struct {
	VNI  uint32
	Addr netip.Addr
}

func (s *FloodVtep) unmarshal(b []byte) error {
	if len(b) < 24 {
		return fmt.Errorf("FloodVtep: buffer too short: %d < 24", len(b))
	}
	s.VNI = uint32(getU32(b, 0))
	s.Addr = getL3Addr(b, 4)
	return nil
}

func (s *FloodVtep) marshal() []byte {
	b := make([]byte, 24)
	putU32(b, 0, uint32(s.VNI))
	putL3Addr(b, 4, s.Addr)
	return b
}

type FloodEntry struct {
	Type  FloodType
	VRFID uint16
	Vtep  FloodVtep
}

func (s *FloodEntry) unmarshal(b []byte) error {
	if len(b) < 28 {
		return fmt.Errorf("FloodEntry: buffer too short: %d < 28", len(b))
	}
	s.Type = FloodType(getU8(b, 0))
	s.VRFID = uint16(getU16(b, 2))
	if err := s.Vtep.unmarshal(b[0:24]); err != nil {
		return err
	}
	return nil
}

func (s *FloodEntry) marshal() []byte {
	b := make([]byte, 28)
	putU8(b, 0, uint8(s.Type))
	putU16(b, 2, uint16(s.VRFID))
	copy(b[0:], s.Vtep.marshal())
	return b
}

type FloodAddReq struct {
	Entry   FloodEntry
	ExistOk bool
}

func (s *FloodAddReq) unmarshal(b []byte) error {
	if len(b) < 32 {
		return fmt.Errorf("FloodAddReq: buffer too short: %d < 32", len(b))
	}
	if err := s.Entry.unmarshal(b[0:28]); err != nil {
		return err
	}
	s.ExistOk = getBool(b, 28)
	return nil
}

func (s *FloodAddReq) marshal() []byte {
	b := make([]byte, 32)
	copy(b[0:], s.Entry.marshal())
	putBool(b, 28, s.ExistOk)
	return b
}

type FloodDelReq struct {
	Entry     FloodEntry
	MissingOk bool
}

func (s *FloodDelReq) unmarshal(b []byte) error {
	if len(b) < 32 {
		return fmt.Errorf("FloodDelReq: buffer too short: %d < 32", len(b))
	}
	if err := s.Entry.unmarshal(b[0:28]); err != nil {
		return err
	}
	s.MissingOk = getBool(b, 28)
	return nil
}

func (s *FloodDelReq) marshal() []byte {
	b := make([]byte, 32)
	copy(b[0:], s.Entry.marshal())
	putBool(b, 28, s.MissingOk)
	return b
}

type FloodListReq struct {
	Type  FloodType
	VRFID uint16
}

func (s *FloodListReq) unmarshal(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("FloodListReq: buffer too short: %d < 4", len(b))
	}
	s.Type = FloodType(getU8(b, 0))
	s.VRFID = uint16(getU16(b, 2))
	return nil
}

func (s *FloodListReq) marshal() []byte {
	b := make([]byte, 4)
	putU8(b, 0, uint8(s.Type))
	putU16(b, 2, uint16(s.VRFID))
	return b
}

// Request type constants.
const (
	grFloodList    uint32 = 0xbabe0009
	grFloodDel     uint32 = 0xbabe0008
	grFloodAdd     uint32 = 0xbabe0007
	grFDBConfigSet uint32 = 0xbabe0006
	grFDBConfigGet uint32 = 0xbabe0005
	grFDBList      uint32 = 0xbabe0004
	grFDBFlush     uint32 = 0xbabe0003
	grFDBDel       uint32 = 0xbabe0002
	grFDBAdd       uint32 = 0xbabe0001
)

// Event type constants.
const (
	EventFloodDel  uint32 = 0xbabe1005
	EventFloodAdd  uint32 = 0xbabe1004
	EventFDBUpdate uint32 = 0xbabe1003
	EventFDBDel    uint32 = 0xbabe1002
	EventFDBAdd    uint32 = 0xbabe1001
)

func (c *Client) FloodList(req *FloodListReq) iter.Seq2[*FloodEntry, error] {
	return streamIter[FloodEntry](c, grFloodList, req.marshal())
}

func (c *Client) FloodDel(req *FloodDelReq) error {
	return c.sendOnly(grFloodDel, req.marshal())
}

func (c *Client) FloodAdd(req *FloodAddReq) error {
	return c.sendOnly(grFloodAdd, req.marshal())
}

func (c *Client) FDBConfigSet(req *FDBConfigSetReq) error {
	return c.sendOnly(grFDBConfigSet, req.marshal())
}

func (c *Client) FDBConfigGet() (*FDBConfigGetResp, error) {
	data, err := c.sendRecv(grFDBConfigGet, nil)
	if err != nil {
		return nil, err
	}
	resp := new(FDBConfigGetResp)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func (c *Client) FDBList(req *FDBListReq) iter.Seq2[*FDBEntry, error] {
	return streamIter[FDBEntry](c, grFDBList, req.marshal())
}

func (c *Client) FDBFlush(req *FDBFlushReq) error {
	return c.sendOnly(grFDBFlush, req.marshal())
}

func (c *Client) FDBDel(req *FDBDelReq) error {
	return c.sendOnly(grFDBDel, req.marshal())
}

func (c *Client) FDBAdd(req *FDBAddReq) error {
	return c.sendOnly(grFDBAdd, req.marshal())
}

func init() {
	registerEventDecoder(EventFloodDel, func(b []byte) (any, error) {
		v := new(FloodEntry)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventFloodAdd, func(b []byte) (any, error) {
		v := new(FloodEntry)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventFDBUpdate, func(b []byte) (any, error) {
		v := new(FDBEntry)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventFDBDel, func(b []byte) (any, error) {
		v := new(FDBEntry)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventFDBAdd, func(b []byte) (any, error) {
		v := new(FDBEntry)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
}
