// Code generated by devtools/gen-go.py; DO NOT EDIT.

package grout

import (
	"fmt"
	"iter"
	"net/netip"
)

type IP6Ifaddr struct {
	IfaceID uint16
	Addr    IPv6Net
}

func (s *IP6Ifaddr) unmarshal(b []byte) error {
	if len(b) < 20 {
		return fmt.Errorf("IP6Ifaddr: buffer too short: %d < 20", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.Addr = getIPv6Net(b, 2, 18)
	return nil
}

func (s *IP6Ifaddr) marshal() []byte {
	b := make([]byte, 20)
	putU16(b, 0, uint16(s.IfaceID))
	putIPv6Net(b, 2, 18, s.Addr)
	return b
}

type IP6Route struct {
	Dest   IPv6Net
	VRFID  uint16
	Origin NHOrigin
	NH     Nexthop
}

func (s *IP6Route) unmarshal(b []byte) error {
	if len(b) < 36 {
		return fmt.Errorf("IP6Route: buffer too short: %d < 36", len(b))
	}
	s.Dest = getIPv6Net(b, 0, 16)
	s.VRFID = uint16(getU16(b, 18))
	s.Origin = NHOrigin(getU8(b, 20))
	if err := s.NH.unmarshal(b[24:]); err != nil {
		return err
	}
	return nil
}

func (s *IP6Route) marshal() []byte {
	b := make([]byte, 36)
	putIPv6Net(b, 0, 16, s.Dest)
	putU16(b, 18, uint16(s.VRFID))
	putU8(b, 20, uint8(s.Origin))
	{
		d := s.NH.marshal()
		copy(b[24:], d[:min(len(d), len(b)-24)])
		if len(d) > 12 {
			b = append(b, d[12:]...)
		}
	}
	return b
}

type IP6RouteAddReq struct {
	VRFID   uint16
	Dest    IPv6Net
	NH      netip.Addr
	NHID    uint32
	Origin  NHOrigin
	ExistOk uint8
}

func (s *IP6RouteAddReq) unmarshal(b []byte) error {
	if len(b) < 44 {
		return fmt.Errorf("IP6RouteAddReq: buffer too short: %d < 44", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	s.Dest = getIPv6Net(b, 2, 18)
	s.NH = getIPv6(b, 19)
	s.NHID = uint32(getU32(b, 36))
	s.Origin = NHOrigin(getU8(b, 40))
	s.ExistOk = uint8(getU8(b, 41))
	return nil
}

func (s *IP6RouteAddReq) marshal() []byte {
	b := make([]byte, 44)
	putU16(b, 0, uint16(s.VRFID))
	putIPv6Net(b, 2, 18, s.Dest)
	putIPv6(b, 19, s.NH)
	putU32(b, 36, uint32(s.NHID))
	putU8(b, 40, uint8(s.Origin))
	putU8(b, 41, uint8(s.ExistOk))
	return b
}

type IP6RouteDelReq struct {
	VRFID     uint16
	Dest      IPv6Net
	MissingOk uint8
}

func (s *IP6RouteDelReq) unmarshal(b []byte) error {
	if len(b) < 20 {
		return fmt.Errorf("IP6RouteDelReq: buffer too short: %d < 20", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	s.Dest = getIPv6Net(b, 2, 18)
	s.MissingOk = uint8(getU8(b, 19))
	return nil
}

func (s *IP6RouteDelReq) marshal() []byte {
	b := make([]byte, 20)
	putU16(b, 0, uint16(s.VRFID))
	putIPv6Net(b, 2, 18, s.Dest)
	putU8(b, 19, uint8(s.MissingOk))
	return b
}

type IP6RouteGetReq struct {
	VRFID uint16
	Dest  netip.Addr
}

func (s *IP6RouteGetReq) unmarshal(b []byte) error {
	if len(b) < 18 {
		return fmt.Errorf("IP6RouteGetReq: buffer too short: %d < 18", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	s.Dest = getIPv6(b, 2)
	return nil
}

func (s *IP6RouteGetReq) marshal() []byte {
	b := make([]byte, 18)
	putU16(b, 0, uint16(s.VRFID))
	putIPv6(b, 2, s.Dest)
	return b
}

type IP6RouteGetResp struct {
	NH Nexthop
}

func (s *IP6RouteGetResp) unmarshal(b []byte) error {
	if len(b) < 12 {
		return fmt.Errorf("IP6RouteGetResp: buffer too short: %d < 12", len(b))
	}
	if err := s.NH.unmarshal(b[0:]); err != nil {
		return err
	}
	return nil
}

func (s *IP6RouteGetResp) marshal() []byte {
	b := make([]byte, 12)
	{
		d := s.NH.marshal()
		copy(b[0:], d[:min(len(d), len(b)-0)])
		if len(d) > 12 {
			b = append(b, d[12:]...)
		}
	}
	return b
}

type IP6RouteListReq struct {
	VRFID    uint16
	MaxCount uint16
}

func (s *IP6RouteListReq) unmarshal(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("IP6RouteListReq: buffer too short: %d < 4", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	s.MaxCount = uint16(getU16(b, 2))
	return nil
}

func (s *IP6RouteListReq) marshal() []byte {
	b := make([]byte, 4)
	putU16(b, 0, uint16(s.VRFID))
	putU16(b, 2, uint16(s.MaxCount))
	return b
}

type IP6AddrAddReq struct {
	Addr    IP6Ifaddr
	ExistOk uint8
}

func (s *IP6AddrAddReq) unmarshal(b []byte) error {
	if len(b) < 22 {
		return fmt.Errorf("IP6AddrAddReq: buffer too short: %d < 22", len(b))
	}
	if err := s.Addr.unmarshal(b[0:20]); err != nil {
		return err
	}
	s.ExistOk = uint8(getU8(b, 20))
	return nil
}

func (s *IP6AddrAddReq) marshal() []byte {
	b := make([]byte, 22)
	copy(b[0:], s.Addr.marshal())
	putU8(b, 20, uint8(s.ExistOk))
	return b
}

type IP6AddrDelReq struct {
	Addr      IP6Ifaddr
	MissingOk uint8
}

func (s *IP6AddrDelReq) unmarshal(b []byte) error {
	if len(b) < 22 {
		return fmt.Errorf("IP6AddrDelReq: buffer too short: %d < 22", len(b))
	}
	if err := s.Addr.unmarshal(b[0:20]); err != nil {
		return err
	}
	s.MissingOk = uint8(getU8(b, 20))
	return nil
}

func (s *IP6AddrDelReq) marshal() []byte {
	b := make([]byte, 22)
	copy(b[0:], s.Addr.marshal())
	putU8(b, 20, uint8(s.MissingOk))
	return b
}

type IP6AddrListReq struct {
	VRFID   uint16
	IfaceID uint16
}

func (s *IP6AddrListReq) unmarshal(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("IP6AddrListReq: buffer too short: %d < 4", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	s.IfaceID = uint16(getU16(b, 2))
	return nil
}

func (s *IP6AddrListReq) marshal() []byte {
	b := make([]byte, 4)
	putU16(b, 0, uint16(s.VRFID))
	putU16(b, 2, uint16(s.IfaceID))
	return b
}

type IP6AddrFlushReq struct {
	IfaceID uint16
}

func (s *IP6AddrFlushReq) unmarshal(b []byte) error {
	if len(b) < 2 {
		return fmt.Errorf("IP6AddrFlushReq: buffer too short: %d < 2", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	return nil
}

func (s *IP6AddrFlushReq) marshal() []byte {
	b := make([]byte, 2)
	putU16(b, 0, uint16(s.IfaceID))
	return b
}

type Fib6Info struct {
	VRFID      uint16
	MaxRoutes  uint32
	UsedRoutes uint32
	NumTbl8    uint32
	UsedTbl8   uint32
}

func (s *Fib6Info) unmarshal(b []byte) error {
	if len(b) < 20 {
		return fmt.Errorf("Fib6Info: buffer too short: %d < 20", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	s.MaxRoutes = uint32(getU32(b, 4))
	s.UsedRoutes = uint32(getU32(b, 8))
	s.NumTbl8 = uint32(getU32(b, 12))
	s.UsedTbl8 = uint32(getU32(b, 16))
	return nil
}

func (s *Fib6Info) marshal() []byte {
	b := make([]byte, 20)
	putU16(b, 0, uint16(s.VRFID))
	putU32(b, 4, uint32(s.MaxRoutes))
	putU32(b, 8, uint32(s.UsedRoutes))
	putU32(b, 12, uint32(s.NumTbl8))
	putU32(b, 16, uint32(s.UsedTbl8))
	return b
}

type IP6FIBDefaultSetReq struct {
	MaxRoutes uint32
}

func (s *IP6FIBDefaultSetReq) unmarshal(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("IP6FIBDefaultSetReq: buffer too short: %d < 4", len(b))
	}
	s.MaxRoutes = uint32(getU32(b, 0))
	return nil
}

func (s *IP6FIBDefaultSetReq) marshal() []byte {
	b := make([]byte, 4)
	putU32(b, 0, uint32(s.MaxRoutes))
	return b
}

type IP6FIBInfoListReq struct {
	VRFID uint16
}

func (s *IP6FIBInfoListReq) unmarshal(b []byte) error {
	if len(b) < 2 {
		return fmt.Errorf("IP6FIBInfoListReq: buffer too short: %d < 2", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	return nil
}

func (s *IP6FIBInfoListReq) marshal() []byte {
	b := make([]byte, 2)
	putU16(b, 0, uint16(s.VRFID))
	return b
}

type IP6RASetReq struct {
	IfaceID     uint16
	SetInterval uint16
	SetLifetime uint16
	Interval    uint16
	Lifetime    uint16
}

func (s *IP6RASetReq) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("IP6RASetReq: buffer too short: %d < 8", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.SetInterval = uint16((b[0] >> 0) & 1)
	s.SetLifetime = uint16((b[0] >> 1) & 1)
	s.Interval = uint16(getU16(b, 4))
	s.Lifetime = uint16(getU16(b, 6))
	return nil
}

func (s *IP6RASetReq) marshal() []byte {
	b := make([]byte, 8)
	putU16(b, 0, uint16(s.IfaceID))
	b[0] |= byte((uint8(s.SetInterval) & 1) << 0)
	b[0] |= byte((uint8(s.SetLifetime) & 1) << 1)
	putU16(b, 4, uint16(s.Interval))
	putU16(b, 6, uint16(s.Lifetime))
	return b
}

type IP6RAClearReq struct {
	IfaceID uint16
}

func (s *IP6RAClearReq) unmarshal(b []byte) error {
	if len(b) < 2 {
		return fmt.Errorf("IP6RAClearReq: buffer too short: %d < 2", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	return nil
}

func (s *IP6RAClearReq) marshal() []byte {
	b := make([]byte, 2)
	putU16(b, 0, uint16(s.IfaceID))
	return b
}

type IP6RAShowReq struct {
	IfaceID uint16
}

func (s *IP6RAShowReq) unmarshal(b []byte) error {
	if len(b) < 2 {
		return fmt.Errorf("IP6RAShowReq: buffer too short: %d < 2", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	return nil
}

func (s *IP6RAShowReq) marshal() []byte {
	b := make([]byte, 2)
	putU16(b, 0, uint16(s.IfaceID))
	return b
}

type IP6RAConf struct {
	Enabled  bool
	IfaceID  uint16
	Interval uint16
	Lifetime uint16
}

func (s *IP6RAConf) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("IP6RAConf: buffer too short: %d < 8", len(b))
	}
	s.Enabled = getBool(b, 0)
	s.IfaceID = uint16(getU16(b, 2))
	s.Interval = uint16(getU16(b, 4))
	s.Lifetime = uint16(getU16(b, 6))
	return nil
}

func (s *IP6RAConf) marshal() []byte {
	b := make([]byte, 8)
	putBool(b, 0, s.Enabled)
	putU16(b, 2, uint16(s.IfaceID))
	putU16(b, 4, uint16(s.Interval))
	putU16(b, 6, uint16(s.Lifetime))
	return b
}

type IP6ICMPSendReq struct {
	Addr   netip.Addr
	Iface  uint16
	VRF    uint16
	Ident  uint16
	SeqNum uint16
	Ttl    uint8
}

func (s *IP6ICMPSendReq) unmarshal(b []byte) error {
	if len(b) < 26 {
		return fmt.Errorf("IP6ICMPSendReq: buffer too short: %d < 26", len(b))
	}
	s.Addr = getIPv6(b, 0)
	s.Iface = uint16(getU16(b, 16))
	s.VRF = uint16(getU16(b, 18))
	s.Ident = uint16(getU16(b, 20))
	s.SeqNum = uint16(getU16(b, 22))
	s.Ttl = uint8(getU8(b, 24))
	return nil
}

func (s *IP6ICMPSendReq) marshal() []byte {
	b := make([]byte, 26)
	putIPv6(b, 0, s.Addr)
	putU16(b, 16, uint16(s.Iface))
	putU16(b, 18, uint16(s.VRF))
	putU16(b, 20, uint16(s.Ident))
	putU16(b, 22, uint16(s.SeqNum))
	putU8(b, 24, uint8(s.Ttl))
	return b
}

type IP6ICMPRecvReq struct {
	Ident  uint16
	SeqNum uint16
}

func (s *IP6ICMPRecvReq) unmarshal(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("IP6ICMPRecvReq: buffer too short: %d < 4", len(b))
	}
	s.Ident = uint16(getU16(b, 0))
	s.SeqNum = uint16(getU16(b, 2))
	return nil
}

func (s *IP6ICMPRecvReq) marshal() []byte {
	b := make([]byte, 4)
	putU16(b, 0, uint16(s.Ident))
	putU16(b, 2, uint16(s.SeqNum))
	return b
}

type IP6ICMPRecvResp struct {
	Type         uint8
	Code         uint8
	Ttl          uint8
	Ident        uint16
	SeqNum       uint16
	SrcAddr      netip.Addr
	ResponseTime int64
}

func (s *IP6ICMPRecvResp) unmarshal(b []byte) error {
	if len(b) < 32 {
		return fmt.Errorf("IP6ICMPRecvResp: buffer too short: %d < 32", len(b))
	}
	s.Type = uint8(getU8(b, 0))
	s.Code = uint8(getU8(b, 1))
	s.Ttl = uint8(getU8(b, 2))
	s.Ident = uint16(getU16(b, 4))
	s.SeqNum = uint16(getU16(b, 6))
	s.SrcAddr = getIPv6(b, 8)
	s.ResponseTime = int64(getU64(b, 24))
	return nil
}

func (s *IP6ICMPRecvResp) marshal() []byte {
	b := make([]byte, 32)
	putU8(b, 0, uint8(s.Type))
	putU8(b, 1, uint8(s.Code))
	putU8(b, 2, uint8(s.Ttl))
	putU16(b, 4, uint16(s.Ident))
	putU16(b, 6, uint16(s.SeqNum))
	putIPv6(b, 8, s.SrcAddr)
	putU64(b, 24, uint64(s.ResponseTime))
	return b
}

// Request type constants.
const (
	grIP6Icmp6Recv     uint32 = 0xfeed000f
	grIP6Icmp6Send     uint32 = 0xfeed000e
	grIP6IfaceRAShow   uint32 = 0xfeed000d
	grIP6IfaceRAClear  uint32 = 0xfeed000c
	grIP6IfaceRASet    uint32 = 0xfeed000b
	grIP6FIBInfoList   uint32 = 0xfeed000a
	grIP6FIBDefaultSet uint32 = 0xfeed0009
	grIP6AddrFlush     uint32 = 0xfeed0008
	grIP6AddrList      uint32 = 0xfeed0007
	grIP6AddrDel       uint32 = 0xfeed0006
	grIP6AddrAdd       uint32 = 0xfeed0005
	grIP6RouteList     uint32 = 0xfeed0004
	grIP6RouteGet      uint32 = 0xfeed0003
	grIP6RouteDel      uint32 = 0xfeed0002
	grIP6RouteAdd      uint32 = 0xfeed0001
)

// Event type constants.
const (
	EventIP6RouteDel uint32 = 0xfeed1004
	EventIP6RouteAdd uint32 = 0xfeed1003
	EventIP6AddrDel  uint32 = 0xfeed1002
	EventIP6AddrAdd  uint32 = 0xfeed1001
)

func (c *Client) IP6Icmp6Recv(req *IP6ICMPRecvReq) (*IP6ICMPRecvResp, error) {
	data, err := c.sendRecv(grIP6Icmp6Recv, req.marshal())
	if err != nil {
		return nil, err
	}
	resp := new(IP6ICMPRecvResp)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func (c *Client) IP6Icmp6Send(req *IP6ICMPSendReq) error {
	return c.sendOnly(grIP6Icmp6Send, req.marshal())
}

func (c *Client) IP6IfaceRAShow(req *IP6RAShowReq) iter.Seq2[*IP6RAConf, error] {
	return streamIter[IP6RAConf](c, grIP6IfaceRAShow, req.marshal())
}

func (c *Client) IP6IfaceRAClear(req *IP6RAClearReq) error {
	return c.sendOnly(grIP6IfaceRAClear, req.marshal())
}

func (c *Client) IP6IfaceRASet(req *IP6RASetReq) error {
	return c.sendOnly(grIP6IfaceRASet, req.marshal())
}

func (c *Client) IP6FIBInfoList(req *IP6FIBInfoListReq) iter.Seq2[*Fib6Info, error] {
	return streamIter[Fib6Info](c, grIP6FIBInfoList, req.marshal())
}

func (c *Client) IP6FIBDefaultSet(req *IP6FIBDefaultSetReq) error {
	return c.sendOnly(grIP6FIBDefaultSet, req.marshal())
}

func (c *Client) IP6AddrFlush(req *IP6AddrFlushReq) error {
	return c.sendOnly(grIP6AddrFlush, req.marshal())
}

func (c *Client) IP6AddrList(req *IP6AddrListReq) iter.Seq2[*IP6Ifaddr, error] {
	return streamIter[IP6Ifaddr](c, grIP6AddrList, req.marshal())
}

func (c *Client) IP6AddrDel(req *IP6AddrDelReq) error {
	return c.sendOnly(grIP6AddrDel, req.marshal())
}

func (c *Client) IP6AddrAdd(req *IP6AddrAddReq) error {
	return c.sendOnly(grIP6AddrAdd, req.marshal())
}

func (c *Client) IP6RouteList(req *IP6RouteListReq) iter.Seq2[*IP6Route, error] {
	return streamIter[IP6Route](c, grIP6RouteList, req.marshal())
}

func (c *Client) IP6RouteGet(req *IP6RouteGetReq) (*IP6RouteGetResp, error) {
	data, err := c.sendRecv(grIP6RouteGet, req.marshal())
	if err != nil {
		return nil, err
	}
	resp := new(IP6RouteGetResp)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func (c *Client) IP6RouteDel(req *IP6RouteDelReq) error {
	return c.sendOnly(grIP6RouteDel, req.marshal())
}

func (c *Client) IP6RouteAdd(req *IP6RouteAddReq) error {
	return c.sendOnly(grIP6RouteAdd, req.marshal())
}

func init() {
	registerEventDecoder(EventIP6RouteDel, func(b []byte) (any, error) {
		v := new(IP6Route)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventIP6RouteAdd, func(b []byte) (any, error) {
		v := new(IP6Route)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventIP6AddrDel, func(b []byte) (any, error) {
		v := new(IP6Ifaddr)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventIP6AddrAdd, func(b []byte) (any, error) {
		v := new(IP6Ifaddr)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
}
