// Code generated by devtools/gen-go.py; DO NOT EDIT.

package grout

import (
	"fmt"
	"iter"
	"net/netip"
)

type ConnState uint32

const (
	Closed      ConnState = 0
	New         ConnState = 1
	SimsynSent  ConnState = 2
	SynReceived ConnState = 3
	Established ConnState = 4
	FinSent     ConnState = 5
	FinReceived ConnState = 6
	CloseWait   ConnState = 7
	FinWait     ConnState = 8
	Closing     ConnState = 9
	LastAck     ConnState = 10
	TimeWait    ConnState = 11
)

type ConntrackFlow struct {
	Src   netip.Addr
	Dst   netip.Addr
	SrcID uint16
	DstID uint16
}

func (s *ConntrackFlow) unmarshal(b []byte) error {
	if len(b) < 12 {
		return fmt.Errorf("ConntrackFlow: buffer too short: %d < 12", len(b))
	}
	s.Src = getIPv4(b, 0)
	s.Dst = getIPv4(b, 4)
	s.SrcID = uint16(getU16(b, 8))
	s.DstID = uint16(getU16(b, 10))
	return nil
}

func (s *ConntrackFlow) marshal() []byte {
	b := make([]byte, 12)
	putIPv4(b, 0, s.Src)
	putIPv4(b, 4, s.Dst)
	putU16(b, 8, uint16(s.SrcID))
	putU16(b, 10, uint16(s.DstID))
	return b
}

type Conntrack struct {
	IfaceID    uint16
	AF         AddrFamily
	Proto      uint8
	FwdFlow    ConntrackFlow
	RevFlow    ConntrackFlow
	LastUpdate int64
	ID         uint32
	State      ConnState
}

func (s *Conntrack) unmarshal(b []byte) error {
	if len(b) < 48 {
		return fmt.Errorf("Conntrack: buffer too short: %d < 48", len(b))
	}
	s.IfaceID = uint16(getU16(b, 0))
	s.AF = AddrFamily(getU8(b, 2))
	s.Proto = uint8(getU8(b, 3))
	if err := s.FwdFlow.unmarshal(b[4:16]); err != nil {
		return err
	}
	if err := s.RevFlow.unmarshal(b[16:28]); err != nil {
		return err
	}
	s.LastUpdate = int64(getU64(b, 32))
	s.ID = uint32(getU32(b, 40))
	s.State = ConnState(getU8(b, 44))
	return nil
}

func (s *Conntrack) marshal() []byte {
	b := make([]byte, 48)
	putU16(b, 0, uint16(s.IfaceID))
	putU8(b, 2, uint8(s.AF))
	putU8(b, 3, uint8(s.Proto))
	copy(b[4:], s.FwdFlow.marshal())
	copy(b[16:], s.RevFlow.marshal())
	putU64(b, 32, uint64(s.LastUpdate))
	putU32(b, 40, uint32(s.ID))
	putU32(b, 44, uint32(s.State))
	return b
}

type ConntrackConfig struct {
	MaxCount                 uint32
	TimeoutClosedSec         uint32
	TimeoutNewSec            uint32
	TimeoutUDPEstablishedSec uint32
	TimeoutTCPEstablishedSec uint32
	TimeoutHalfCloseSec      uint32
	TimeoutTimeWaitSec       uint32
}

func (s *ConntrackConfig) unmarshal(b []byte) error {
	if len(b) < 28 {
		return fmt.Errorf("ConntrackConfig: buffer too short: %d < 28", len(b))
	}
	s.MaxCount = uint32(getU32(b, 0))
	s.TimeoutClosedSec = uint32(getU32(b, 4))
	s.TimeoutNewSec = uint32(getU32(b, 8))
	s.TimeoutUDPEstablishedSec = uint32(getU32(b, 12))
	s.TimeoutTCPEstablishedSec = uint32(getU32(b, 16))
	s.TimeoutHalfCloseSec = uint32(getU32(b, 20))
	s.TimeoutTimeWaitSec = uint32(getU32(b, 24))
	return nil
}

func (s *ConntrackConfig) marshal() []byte {
	b := make([]byte, 28)
	putU32(b, 0, uint32(s.MaxCount))
	putU32(b, 4, uint32(s.TimeoutClosedSec))
	putU32(b, 8, uint32(s.TimeoutNewSec))
	putU32(b, 12, uint32(s.TimeoutUDPEstablishedSec))
	putU32(b, 16, uint32(s.TimeoutTCPEstablishedSec))
	putU32(b, 20, uint32(s.TimeoutHalfCloseSec))
	putU32(b, 24, uint32(s.TimeoutTimeWaitSec))
	return b
}

type ConntrackConfGetResp struct {
	MaxCount                 uint32
	TimeoutClosedSec         uint32
	TimeoutNewSec            uint32
	TimeoutUDPEstablishedSec uint32
	TimeoutTCPEstablishedSec uint32
	TimeoutHalfCloseSec      uint32
	TimeoutTimeWaitSec       uint32
	UsedCount                uint32
}

func (s *ConntrackConfGetResp) unmarshal(b []byte) error {
	if len(b) < 32 {
		return fmt.Errorf("ConntrackConfGetResp: buffer too short: %d < 32", len(b))
	}
	s.MaxCount = uint32(getU32(b, 0))
	s.TimeoutClosedSec = uint32(getU32(b, 4))
	s.TimeoutNewSec = uint32(getU32(b, 8))
	s.TimeoutUDPEstablishedSec = uint32(getU32(b, 12))
	s.TimeoutTCPEstablishedSec = uint32(getU32(b, 16))
	s.TimeoutHalfCloseSec = uint32(getU32(b, 20))
	s.TimeoutTimeWaitSec = uint32(getU32(b, 24))
	s.UsedCount = uint32(getU32(b, 28))
	return nil
}

func (s *ConntrackConfGetResp) marshal() []byte {
	b := make([]byte, 32)
	putU32(b, 0, uint32(s.MaxCount))
	putU32(b, 4, uint32(s.TimeoutClosedSec))
	putU32(b, 8, uint32(s.TimeoutNewSec))
	putU32(b, 12, uint32(s.TimeoutUDPEstablishedSec))
	putU32(b, 16, uint32(s.TimeoutTCPEstablishedSec))
	putU32(b, 20, uint32(s.TimeoutHalfCloseSec))
	putU32(b, 24, uint32(s.TimeoutTimeWaitSec))
	putU32(b, 28, uint32(s.UsedCount))
	return b
}

type ConntrackConfSetReq struct {
	MaxCount                 uint32
	TimeoutClosedSec         uint32
	TimeoutNewSec            uint32
	TimeoutUDPEstablishedSec uint32
	TimeoutTCPEstablishedSec uint32
	TimeoutHalfCloseSec      uint32
	TimeoutTimeWaitSec       uint32
}

func (s *ConntrackConfSetReq) unmarshal(b []byte) error {
	if len(b) < 28 {
		return fmt.Errorf("ConntrackConfSetReq: buffer too short: %d < 28", len(b))
	}
	s.MaxCount = uint32(getU32(b, 0))
	s.TimeoutClosedSec = uint32(getU32(b, 4))
	s.TimeoutNewSec = uint32(getU32(b, 8))
	s.TimeoutUDPEstablishedSec = uint32(getU32(b, 12))
	s.TimeoutTCPEstablishedSec = uint32(getU32(b, 16))
	s.TimeoutHalfCloseSec = uint32(getU32(b, 20))
	s.TimeoutTimeWaitSec = uint32(getU32(b, 24))
	return nil
}

func (s *ConntrackConfSetReq) marshal() []byte {
	b := make([]byte, 28)
	putU32(b, 0, uint32(s.MaxCount))
	putU32(b, 4, uint32(s.TimeoutClosedSec))
	putU32(b, 8, uint32(s.TimeoutNewSec))
	putU32(b, 12, uint32(s.TimeoutUDPEstablishedSec))
	putU32(b, 16, uint32(s.TimeoutTCPEstablishedSec))
	putU32(b, 20, uint32(s.TimeoutHalfCloseSec))
	putU32(b, 24, uint32(s.TimeoutTimeWaitSec))
	return b
}

// Request type constants.
const (
	grConntrackConfSet uint32 = 0xc0c00004
	grConntrackConfGet uint32 = 0xc0c00003
	grConntrackFlush   uint32 = 0xc0c00002
	grConntrackList    uint32 = 0xc0c00001
)

func (c *Client) ConntrackConfSet(req *ConntrackConfSetReq) error {
	return c.sendOnly(grConntrackConfSet, req.marshal())
}

func (c *Client) ConntrackConfGet() (*ConntrackConfGetResp, error) {
	data, err := c.sendRecv(grConntrackConfGet, nil)
	if err != nil {
		return nil, err
	}
	resp := new(ConntrackConfGetResp)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func (c *Client) ConntrackFlush() error {
	return c.sendOnly(grConntrackFlush, nil)
}

func (c *Client) ConntrackList() iter.Seq2[*Conntrack, error] {
	return streamIter[Conntrack](c, grConntrackList, nil)
}
