// Code generated by devtools/gen-go.py; DO NOT EDIT.

package grout

import (
	"fmt"
	"iter"
	"net/netip"
)

type NHState uint8

const (
	NHSNew       NHState = 0
	NHSPending   NHState = 1
	NHSReachable NHState = 2
	NHSStale     NHState = 3
	NHSFailed    NHState = 4
)

type NHFlags uint8

const (
	NHFStatic  NHFlags = 1
	NHFLocal   NHFlags = 2
	NHFGateway NHFlags = 4
	NHFLink    NHFlags = 8
	NHFMcast   NHFlags = 16
	NHFRemote  NHFlags = 32
)

type NHType uint8

const (
	NHTL3        NHType = 0
	NHTSR6Output NHType = 1
	NHTSR6Local  NHType = 2
	NHTDNAT      NHType = 3
	NHTBlackhole NHType = 4
	NHTReject    NHType = 5
	NHTGroup     NHType = 6
)

type NHOrigin uint8

const (
	NHOriginUnspec     NHOrigin = 0
	NHOriginRedirect   NHOrigin = 1
	NHOriginLink       NHOrigin = 2
	NHOriginBoot       NHOrigin = 3
	NHOriginStatic     NHOrigin = 4
	NHOriginGated      NHOrigin = 8
	NHOriginRA         NHOrigin = 9
	NHOriginMRT        NHOrigin = 10
	NHOriginZebra      NHOrigin = 11
	NHOriginBird       NHOrigin = 12
	NHOriginDnrouted   NHOrigin = 13
	NHOriginXorp       NHOrigin = 14
	NHOriginNTK        NHOrigin = 15
	NHOriginDHCP       NHOrigin = 16
	NHOriginMrouted    NHOrigin = 17
	NHOriginKeepalived NHOrigin = 18
	NHOriginBabel      NHOrigin = 42
	NHOriginOpenr      NHOrigin = 99
	NHOriginBGP        NHOrigin = 186
	NHOriginISIS       NHOrigin = 187
	NHOriginOSPF       NHOrigin = 188
	NHOriginRIP        NHOrigin = 189
	NHOriginRipng      NHOrigin = 190
	NHOriginNhrp       NHOrigin = 191
	NHOriginEigrp      NHOrigin = 192
	NHOriginLDP        NHOrigin = 193
	NHOriginSharp      NHOrigin = 194
	NHOriginPBR        NHOrigin = 195
	NHOriginZstatic    NHOrigin = 196
	NHOriginOpenfabric NHOrigin = 197
	NHOriginSrte       NHOrigin = 198
	NHOriginInternal   NHOrigin = 255
)

type NexthopInfoL3 struct {
	State     NHState
	Flags     NHFlags
	AF        AddrFamily
	Prefixlen uint8
	// Addr /* TODO:  */ [0]byte
	Ipv4 netip.Addr
	Ipv6 netip.Addr
	MAC  EtherAddr
}

func (s *NexthopInfoL3) unmarshal(b []byte) error {
	if len(b) < 28 {
		return fmt.Errorf("NexthopInfoL3: buffer too short: %d < 28", len(b))
	}
	s.State = NHState(getU8(b, 0))
	s.Flags = NHFlags(getU8(b, 1))
	s.AF = AddrFamily(getU8(b, 2))
	s.Prefixlen = uint8(getU8(b, 3))
	s.Ipv4 = getIPv4(b, 0)
	s.Ipv6 = getIPv6(b, 0)
	s.MAC = getEther(b, 20)
	return nil
}

func (s *NexthopInfoL3) marshal() []byte {
	b := make([]byte, 28)
	putU8(b, 0, uint8(s.State))
	putU8(b, 1, uint8(s.Flags))
	putU8(b, 2, uint8(s.AF))
	putU8(b, 3, uint8(s.Prefixlen))
	putIPv4(b, 0, s.Ipv4)
	putIPv6(b, 0, s.Ipv6)
	putEther(b, 20, s.MAC)
	return b
}

type NexthopGroupMember struct {
	NHID   uint32
	Weight uint32
}

func (s *NexthopGroupMember) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("NexthopGroupMember: buffer too short: %d < 8", len(b))
	}
	s.NHID = uint32(getU32(b, 0))
	s.Weight = uint32(getU32(b, 4))
	return nil
}

func (s *NexthopGroupMember) marshal() []byte {
	b := make([]byte, 8)
	putU32(b, 0, uint32(s.NHID))
	putU32(b, 4, uint32(s.Weight))
	return b
}

type NexthopInfoGroup struct {
	NMembers uint32
	Members  []NexthopGroupMember
}

func (s *NexthopInfoGroup) unmarshal(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("NexthopInfoGroup: buffer too short: %d < 4", len(b))
	}
	s.NMembers = uint32(getU32(b, 0))
	for off := 4; off+8 <= len(b); off += 8 {
		var elem NexthopGroupMember
		if err := elem.unmarshal(b[off : off+8]); err != nil {
			return err
		}
		s.Members = append(s.Members, elem)
	}
	return nil
}

func (s *NexthopInfoGroup) marshal() []byte {
	b := make([]byte, 4)
	putU32(b, 0, uint32(s.NMembers))
	for i := range s.Members {
		b = append(b, s.Members[i].marshal()...)
	}
	return b
}

type Nexthop struct {
	Type    NHType
	Origin  NHOrigin
	IfaceID uint16
	VRFID   uint16
	NHID    uint32
	Info    any
}

func (s *Nexthop) unmarshal(b []byte) error {
	if len(b) < 12 {
		return fmt.Errorf("Nexthop: buffer too short: %d < 12", len(b))
	}
	s.Type = NHType(getU8(b, 0))
	s.Origin = NHOrigin(getU8(b, 1))
	s.IfaceID = uint16(getU16(b, 2))
	s.VRFID = uint16(getU16(b, 4))
	s.NHID = uint32(getU32(b, 8))
	if len(b) > 12 {
		info := b[12:]
		switch s.Type {
		case NHTL3:
			var v NexthopInfoL3
			if err := v.unmarshal(info); err != nil {
				return err
			}
			s.Info = &v
		case NHTSR6Output:
			var v NexthopInfoSRV6
			if err := v.unmarshal(info); err != nil {
				return err
			}
			s.Info = &v
		case NHTSR6Local:
			var v NexthopInfoSRV6Local
			if err := v.unmarshal(info); err != nil {
				return err
			}
			s.Info = &v
		case NHTDNAT:
			var v NexthopInfoDNAT
			if err := v.unmarshal(info); err != nil {
				return err
			}
			s.Info = &v
		case NHTGroup:
			var v NexthopInfoGroup
			if err := v.unmarshal(info); err != nil {
				return err
			}
			s.Info = &v
		}
	}
	return nil
}

func (s *Nexthop) marshal() []byte {
	b := make([]byte, 12)
	putU8(b, 0, uint8(s.Type))
	putU8(b, 1, uint8(s.Origin))
	putU16(b, 2, uint16(s.IfaceID))
	putU16(b, 4, uint16(s.VRFID))
	putU32(b, 8, uint32(s.NHID))
	if s.Info != nil {
		if m, ok := s.Info.(marshaler); ok {
			b = append(b, m.marshal()...)
		}
	}
	return b
}

type NexthopConfig struct {
	MaxCount               uint32
	LifetimeReachableSec   uint32
	LifetimeUnreachableSec uint32
	MaxHeldPkts            uint16
	MaxUcastProbes         uint8
	MaxBcastProbes         uint8
}

func (s *NexthopConfig) unmarshal(b []byte) error {
	if len(b) < 16 {
		return fmt.Errorf("NexthopConfig: buffer too short: %d < 16", len(b))
	}
	s.MaxCount = uint32(getU32(b, 0))
	s.LifetimeReachableSec = uint32(getU32(b, 4))
	s.LifetimeUnreachableSec = uint32(getU32(b, 8))
	s.MaxHeldPkts = uint16(getU16(b, 12))
	s.MaxUcastProbes = uint8(getU8(b, 14))
	s.MaxBcastProbes = uint8(getU8(b, 15))
	return nil
}

func (s *NexthopConfig) marshal() []byte {
	b := make([]byte, 16)
	putU32(b, 0, uint32(s.MaxCount))
	putU32(b, 4, uint32(s.LifetimeReachableSec))
	putU32(b, 8, uint32(s.LifetimeUnreachableSec))
	putU16(b, 12, uint16(s.MaxHeldPkts))
	putU8(b, 14, uint8(s.MaxUcastProbes))
	putU8(b, 15, uint8(s.MaxBcastProbes))
	return b
}

type NHConfigGetResp struct {
	MaxCount               uint32
	LifetimeReachableSec   uint32
	LifetimeUnreachableSec uint32
	MaxHeldPkts            uint16
	MaxUcastProbes         uint8
	MaxBcastProbes         uint8
	UsedCount              uint32
}

func (s *NHConfigGetResp) unmarshal(b []byte) error {
	if len(b) < 20 {
		return fmt.Errorf("NHConfigGetResp: buffer too short: %d < 20", len(b))
	}
	s.MaxCount = uint32(getU32(b, 0))
	s.LifetimeReachableSec = uint32(getU32(b, 4))
	s.LifetimeUnreachableSec = uint32(getU32(b, 8))
	s.MaxHeldPkts = uint16(getU16(b, 12))
	s.MaxUcastProbes = uint8(getU8(b, 14))
	s.MaxBcastProbes = uint8(getU8(b, 15))
	s.UsedCount = uint32(getU32(b, 16))
	return nil
}

func (s *NHConfigGetResp) marshal() []byte {
	b := make([]byte, 20)
	putU32(b, 0, uint32(s.MaxCount))
	putU32(b, 4, uint32(s.LifetimeReachableSec))
	putU32(b, 8, uint32(s.LifetimeUnreachableSec))
	putU16(b, 12, uint16(s.MaxHeldPkts))
	putU8(b, 14, uint8(s.MaxUcastProbes))
	putU8(b, 15, uint8(s.MaxBcastProbes))
	putU32(b, 16, uint32(s.UsedCount))
	return b
}

type NHConfigSetReq struct {
	MaxCount               uint32
	LifetimeReachableSec   uint32
	LifetimeUnreachableSec uint32
	MaxHeldPkts            uint16
	MaxUcastProbes         uint8
	MaxBcastProbes         uint8
}

func (s *NHConfigSetReq) unmarshal(b []byte) error {
	if len(b) < 16 {
		return fmt.Errorf("NHConfigSetReq: buffer too short: %d < 16", len(b))
	}
	s.MaxCount = uint32(getU32(b, 0))
	s.LifetimeReachableSec = uint32(getU32(b, 4))
	s.LifetimeUnreachableSec = uint32(getU32(b, 8))
	s.MaxHeldPkts = uint16(getU16(b, 12))
	s.MaxUcastProbes = uint8(getU8(b, 14))
	s.MaxBcastProbes = uint8(getU8(b, 15))
	return nil
}

func (s *NHConfigSetReq) marshal() []byte {
	b := make([]byte, 16)
	putU32(b, 0, uint32(s.MaxCount))
	putU32(b, 4, uint32(s.LifetimeReachableSec))
	putU32(b, 8, uint32(s.LifetimeUnreachableSec))
	putU16(b, 12, uint16(s.MaxHeldPkts))
	putU8(b, 14, uint8(s.MaxUcastProbes))
	putU8(b, 15, uint8(s.MaxBcastProbes))
	return b
}

type NHAddReq struct {
	ExistOk uint8
	NH      Nexthop
}

func (s *NHAddReq) unmarshal(b []byte) error {
	if len(b) < 16 {
		return fmt.Errorf("NHAddReq: buffer too short: %d < 16", len(b))
	}
	s.ExistOk = uint8(getU8(b, 0))
	if err := s.NH.unmarshal(b[4:]); err != nil {
		return err
	}
	return nil
}

func (s *NHAddReq) marshal() []byte {
	b := make([]byte, 16)
	putU8(b, 0, uint8(s.ExistOk))
	{
		d := s.NH.marshal()
		copy(b[4:], d[:min(len(d), len(b)-4)])
		if len(d) > 12 {
			b = append(b, d[12:]...)
		}
	}
	return b
}

type NHDelReq struct {
	NHID      uint32
	MissingOk uint8
}

func (s *NHDelReq) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("NHDelReq: buffer too short: %d < 8", len(b))
	}
	s.NHID = uint32(getU32(b, 0))
	s.MissingOk = uint8(getU8(b, 4))
	return nil
}

func (s *NHDelReq) marshal() []byte {
	b := make([]byte, 8)
	putU32(b, 0, uint32(s.NHID))
	putU8(b, 4, uint8(s.MissingOk))
	return b
}

type NHListReq struct {
	VRFID           uint16
	Type            NHType
	MaxCount        uint16
	IncludeInternal bool
}

func (s *NHListReq) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("NHListReq: buffer too short: %d < 8", len(b))
	}
	s.VRFID = uint16(getU16(b, 0))
	s.Type = NHType(getU8(b, 2))
	s.MaxCount = uint16(getU16(b, 4))
	s.IncludeInternal = getBool(b, 6)
	return nil
}

func (s *NHListReq) marshal() []byte {
	b := make([]byte, 8)
	putU16(b, 0, uint16(s.VRFID))
	putU8(b, 2, uint8(s.Type))
	putU16(b, 4, uint16(s.MaxCount))
	putBool(b, 6, s.IncludeInternal)
	return b
}

type NHGetReq struct {
	NHID uint32
}

func (s *NHGetReq) unmarshal(b []byte) error {
	if len(b) < 4 {
		return fmt.Errorf("NHGetReq: buffer too short: %d < 4", len(b))
	}
	s.NHID = uint32(getU32(b, 0))
	return nil
}

func (s *NHGetReq) marshal() []byte {
	b := make([]byte, 4)
	putU32(b, 0, uint32(s.NHID))
	return b
}

type NexthopInfoDNAT struct {
	Match   netip.Addr
	Replace netip.Addr
}

func (s *NexthopInfoDNAT) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("NexthopInfoDNAT: buffer too short: %d < 8", len(b))
	}
	s.Match = getIPv4(b, 0)
	s.Replace = getIPv4(b, 4)
	return nil
}

func (s *NexthopInfoDNAT) marshal() []byte {
	b := make([]byte, 8)
	putIPv4(b, 0, s.Match)
	putIPv4(b, 4, s.Replace)
	return b
}

type NexthopInfoSRV6 struct {
	EncapBehavior SRV6EncapBehavior
	NSeglist      uint8
	Seglist       []netip.Addr
}

func (s *NexthopInfoSRV6) unmarshal(b []byte) error {
	if len(b) < 2 {
		return fmt.Errorf("NexthopInfoSRV6: buffer too short: %d < 2", len(b))
	}
	s.EncapBehavior = SRV6EncapBehavior(getU8(b, 0))
	s.NSeglist = uint8(getU8(b, 1))
	for off := 2; off+16 <= len(b); off += 16 {
		s.Seglist = append(s.Seglist, getIPv6(b, off))
	}
	return nil
}

func (s *NexthopInfoSRV6) marshal() []byte {
	b := make([]byte, 2)
	putU8(b, 0, uint8(s.EncapBehavior))
	putU8(b, 1, uint8(s.NSeglist))
	for _, addr := range s.Seglist {
		a16 := addr.As16()
		b = append(b, a16[:]...)
	}
	return b
}

type NexthopInfoSRV6Local struct {
	OutVRFID  uint16
	Behavior  SRV6Behavior
	Flags     SRV6Flags
	BlockBits uint8
	CsidBits  uint8
}

func (s *NexthopInfoSRV6Local) unmarshal(b []byte) error {
	if len(b) < 8 {
		return fmt.Errorf("NexthopInfoSRV6Local: buffer too short: %d < 8", len(b))
	}
	s.OutVRFID = uint16(getU16(b, 0))
	s.Behavior = SRV6Behavior(getU8(b, 2))
	s.Flags = SRV6Flags(getU8(b, 4))
	s.BlockBits = uint8(getU8(b, 5))
	s.CsidBits = uint8(getU8(b, 6))
	return nil
}

func (s *NexthopInfoSRV6Local) marshal() []byte {
	b := make([]byte, 8)
	putU16(b, 0, uint16(s.OutVRFID))
	putU16(b, 2, uint16(s.Behavior))
	putU8(b, 4, uint8(s.Flags))
	putU8(b, 5, uint8(s.BlockBits))
	putU8(b, 6, uint8(s.CsidBits))
	return b
}

// Request type constants.
const (
	grNHGet       uint32 = 0xacdc2006
	grNHList      uint32 = 0xacdc2005
	grNHDel       uint32 = 0xacdc2004
	grNHAdd       uint32 = 0xacdc2003
	grNHConfigSet uint32 = 0xacdc2002
	grNHConfigGet uint32 = 0xacdc2001
)

// Event type constants.
const (
	EventNexthopUpdate uint32 = 0xacdc3003
	EventNexthopDelete uint32 = 0xacdc3002
	EventNexthopNew    uint32 = 0xacdc3001
)

func (c *Client) NHGet(req *NHGetReq) (*Nexthop, error) {
	data, err := c.sendRecv(grNHGet, req.marshal())
	if err != nil {
		return nil, err
	}
	resp := new(Nexthop)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func (c *Client) NHList(req *NHListReq) iter.Seq2[*Nexthop, error] {
	return streamIter[Nexthop](c, grNHList, req.marshal())
}

func (c *Client) NHDel(req *NHDelReq) error {
	return c.sendOnly(grNHDel, req.marshal())
}

func (c *Client) NHAdd(req *NHAddReq) error {
	return c.sendOnly(grNHAdd, req.marshal())
}

func (c *Client) NHConfigSet(req *NHConfigSetReq) error {
	return c.sendOnly(grNHConfigSet, req.marshal())
}

func (c *Client) NHConfigGet() (*NHConfigGetResp, error) {
	data, err := c.sendRecv(grNHConfigGet, nil)
	if err != nil {
		return nil, err
	}
	resp := new(NHConfigGetResp)
	if data != nil {
		if err := resp.unmarshal(data); err != nil {
			return nil, err
		}
	}
	return resp, nil
}

func init() {
	registerEventDecoder(EventNexthopUpdate, func(b []byte) (any, error) {
		v := new(Nexthop)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventNexthopDelete, func(b []byte) (any, error) {
		v := new(Nexthop)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
	registerEventDecoder(EventNexthopNew, func(b []byte) (any, error) {
		v := new(Nexthop)
		if err := v.unmarshal(b); err != nil {
			return nil, err
		}
		return v, nil
	})
}
