# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025 Robin Jarry
---
name: Apply PR

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    if: github.event.issue.pull_request != null && github.event.comment.body == '/apply'
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      PULL_REQUEST: ${{ github.event.issue.pull_request.url }}
      LOGIN: ${{ github.event.comment.user.login }}

    steps:
      - run: gh auth setup-git

      - uses: actions/checkout@v4
        with:
          repository: DPDK/grout
          ref: main
          persist-credentials: false

      - run: .github/workflows/apply.sh
